### ISSUE TITLE
Automation test cases are failing on Windows 7

### ISSUE THREAD

**Issue by ArunaBalasubramanian** [FlaUI/FlaUI#135]
Hello @Roemer 
My automation test cases run fine on Win8. However, when I execute on Win7, I encounter multiple issues.
The first issue => Throwing an exception on an invoke() command on a hyperlink on the login screen.
![win7invokeissue](https://user-images.githubusercontent.com/24669266/35276027-bd7c1416-0039-11e8-83e5-60c2609b3278.JPG)

Any ideas as why this is happening?

**Comment by Roemer** [comment]
The inner exception `The following constructor parameters did not have matching fixture data` seems to be a message from Xunit. Can you first check if there is an error which is not FlaUI related?

**Comment by emismobile** [comment]
@Roemer I was able to circumvent this error by installing Windows SDK on Win 7 machine.
Does UIA3 library has a support for Windows 7?
I noticed few patterns that are supported in Win8 are not supported in Win7. Do you know why and how to workaround this issue? For example a listview item in Windows 8 supports grid pattern where as the same listview control in Windows 7 doesn't have support for grid pattern.


![win7gridpattern](https://user-images.githubusercontent.com/12909973/35319364-8917fccc-0105-11e8-85e5-abb8d00ca0e2.png)
![win8gridpattern](https://user-images.githubusercontent.com/12909973/35319365-895381ac-0105-11e8-923d-d7c4bb13f862.png)

**Comment by Roemer** [comment]
Great that you found out that the Windows 7 SDK was missing. I'll add that to the FAQ. What happens if you try to install Windows 10 SDK?
What patterns are available when you use UIA2?

**Comment by ArunaBalasubramanian** [comment]
Can we install a higher version Windows SDK on a lower version OS?
For the above list control view, the patterns supported in UIA2 on Windows8 are supported on Windows7 (GridPattern, MultipleViewPattern, SelectionPattern, TablePattern) as well. The issue is with UIA3.
My application is a mix of Winforms and WPF, so I used UIA3 to fall back and support Winforms as well.

**Comment by harrizhasan84** [comment]
Hi,
We ares till facing this issue for Window 7. I have installed Windows 10 SDK in Win 7 too. Some Patterns like Grid are not available for Windows 7 while they are for Win 8 and 10. I need to have same tests to be executed independent of Windows OS, and I need to find an alternative way to read rowcounts in Win 7. any recommendations?

**Comment by Roemer** [comment]
You can manually go thru the child elements if the grid pattern is not supported.

**Comment by Roemer** [comment]
Closing as it is a fact that older Windows does not support all features and Windows 7 is end of life.
