### ISSUE TITLE
FLAUI .netcore compatibilty

### ISSUE THREAD

**Issue by pp1609** [FlaUI/FlaUI#141]
Hi Roemer,

Can you please tell in how much time we can expect FLAUI would be fully compatible with core as we need to decide for which framework to use for windows automation.

Thanks
Preeti

**Comment by pp1609** [comment]
Hi Roemer,

I tried to use FLAUI UIA3 alpha version to check if we can use it in with following code in our .netcore project.
FlaUI.Core.Application app = FlaUI.Core.Application.Attach("JAVAW");
            var automation = new UIA3Automation();
          
            Window[] windows = app.GetAllTopLevelWindows(automation);

But getting following exception:
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at FlaUI.UIA3.UIA3PatternLibrary.get_LegacyIAccessiblePattern()
   at FlaUI.UIA3.UIA3PatternLibrary.get_AllForCurrentFramework()
   at FlaUI.Core.AutomationBase..ctor(IPropertyLibrary propertyLibrary, IEventLibrary eventLibrary, IPatternLibrary patternLibrary)
   at FlaUI.UIA3.UIA3Automation..ctor()
   at testingFlaui.Program.Main(String[] args) in c:\users\e3005457\source\repos\testingFlaui\testingFlaui\Program.cs:line 13

Can you please help with the same.

Thanks

**Comment by Roemer** [comment]
So I investigated a bit.
The following things needed to be removed:
* Capture / Capture Image
* Overlay Manager (for painting a highlighting rectangle)
* IAccessible interface
* WPF Point / Rectangle / Color
* Registry access (For the operation system)
All in all actually not that much.
I have build some experimental nugetpackages with netcore2.0 and netstandard2.0 assemblies. I will attach them here. Do you mind testing them?


[FlaUI.Core&UIA3.NetCore&Standard.zip](https://github.com/Roemer/FlaUI/files/1721648/FlaUI.Core.UIA3.NetCore.Standard.zip)

**Comment by hkoelewijn** [comment]
FYI: I used the nuget package and it works for dotnetstandard2.0. You have any plans to officially support it? Probably some thigs can be resolved by using the Windows.Compatibility package

**Comment by Roemer** [comment]
Thank you for that feedback! Glad it works. Yes I have this on my list, probably for the 3.0.0 release as 2.0.0 will be out soon (rc1 is now on nuget).

**Comment by Roemer** [comment]
I am pretty much finished with the changes.
There are two things missing:
- Get the CI working
- Publish the new depencency Interop.UIAutomationClient to Nuget.

The PR with the changes is https://github.com/Roemer/FlaUI/pull/268

**Comment by Roemer** [comment]
The progress is pretty good. I now even implemented all the new UIA features up to the most recent UIA version and fixed some bugs. I have to wait until the nuget team hands me over the `Interop.UIAutomationClient` nuget package so I can deploy my versioned, fixed interops for UIA3 from https://github.com/Roemer/UIAutomation-Interop. This should be on the 9th of September. I hope to stabilize the CI until then and then you should be prepared for FlaUI v3 with NET Core/Standard compatility!

**Comment by andyb1979** [comment]
Also interested in .netcore support. Can I help? dual-targeting netcore3 as well as net461 is not too difficult

**Comment by Roemer** [comment]
It is pretty much ready. I am now only waiting for NuGet so I can deploy the automation interop packages as a separate package (there is already a package with that name, I want to take that over). I should have that within the next days and then I will release at least an RC.
If you want, you can already try the nuget from here: https://ci.appveyor.com/project/RomanBaeriswyl/flaui/builds/28721339/artifacts
Just don't forget to add the interop nuget from here: https://github.com/Roemer/FlaUI/tree/feature/NetStandard/src/libs as well.

**Comment by LoaStaub** [comment]
Your 2nd Link is broken.
I will give it a try and give feedback

**Comment by Roemer** [comment]
Ah yes, I merged the branch. The nuget can be found here for now: https://github.com/Roemer/FlaUI/tree/master/src/libs

**Comment by andyb1979** [comment]
nice! thanks for letting me know about netcore3 support.

**Comment by LoaStaub** [comment]
when i am installing FlaUI.UIA2 i get the NU1701 error, that the package got recreated by .NET Framework 4.6.1

**Comment by Roemer** [comment]
> when i am installing FlaUI.UIA2 i get the NU1701 error, that the package got recreated by .NET Framework 4.6.1

Are you using the 3.0.0 version from the appveyor link I posted above? If so, could you upload your project?

**Comment by LoaStaub** [comment]
Maybe a problem, that i am using .NET Core 2.2?

**Comment by Roemer** [comment]
Yes, UIA2 does only work in .NET Core 3.0 upwards as System.Windows.Automation only exists in 3.0 or higher. So either go to Core 3.0 or try UIA3.

**Comment by Roemer** [comment]
Version 3.0.0-rc.1 with .NET Core/Standard compatibility is now on NuGet! Please give it a try and report feedback to me (here or on gitter).

**Comment by Roemer** [comment]
Everything seems to work, the final 3.0.0 will be released this week. If you encounter problems, feel free to create new issues.
