### ISSUE TITLE
how to start other windows 10 store apps

### ISSUE THREAD

**Issue by guiflaui** [FlaUI/FlaUI#185]
var app = FlaUI.Core.Application.LaunchStoreApp("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
The above line will start calculator store app and fix the issue "Process has exited, so the requested information is not available",how to start other windows 10 store apps, for example, remote desktop, is there a list? 
because the following line also causes the issue "Process has exited, so the requested information is not available".
var app = FlaUI.Core.Application.Launch("mstsc.exe");

            var automation = new UIA3Automation();
            
            var window = app.GetMainWindow(automation);

thanks in advance.

**Comment by guiflaui** [comment]
tried use application.attach("mstsc.exe"),got 32 bit cannot access 64 bit module error.

**Comment by jrsavs21** [comment]
I had to create a fork to fix this for us.  This line causes the failure:
Logger.Default.Debug($"[Attaching to process:{process.Id}] [Process name:{process.ProcessName}] [Process full path:{process.MainModule.FileName}]");

Its in 
public static Application Attach(Process process) in the file
src/FlaUI.Core/Application.cs 

I just commented it out...  the other option was to change the test tool to run in 64 bit, vs 32..but this broke some coded ui stuff we had.

**Comment by guiflaui** [comment]
Thanks, it fixed the issue, but the variable window is null when I run the following code._
//var app = FlaUI.Core.Application.LaunchStoreApp("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
            var app = FlaUI.Core.Application.Attach("calculator");
            var automation = new UIA3Automation();          
            var window = app.GetMainWindow(automation);

**Comment by guiflaui** [comment]
I already manually open calculator before running the code above.

**Comment by Roemer** [comment]
You cannot attach to StoreApps, they are running inside `ApplicationFrameHost.exe`. The only way to attach to it would be by finding the process via the correct Window which you search on the Desktop element.

**Comment by Roemer** [comment]
Did this solve your issue?

**Comment by guiflaui** [comment]
no

**Comment by Roemer** [comment]
Closed as Store Apps should be launched with `LaunchStoreApp` then it works correctly.
