### ISSUE TITLE
null reference exception in MouseOverlay.Draw

### ISSUE THREAD

**Issue by danielpullwitt** [FlaUI/FlaUI#186]
FlaUI2.0.0rc1 introduces a new problem (not occurring on rc6):

When running the video capturing on our CI system, cursor positions are not reliably available. In this case (User32.GetCursorInfo fails) the CaptureUtilities.CaptureCursor returns null; MouseOverlay.Draw passes this unchecked to Graphics.DrawImage.
rc6 did not attempt to draw anything when User32.GetCursorInfo fails.

**Comment by Roemer** [comment]
Should be fixed in 3.0.0-rc.1 and upwards. Could you give it a try?

**Comment by Roemer** [comment]
This issue is fixed.
