### ISSUE TITLE
Name property is inconsistent in some applications

### ISSUE THREAD

**Issue by hkoelewijn** [FlaUI/FlaUI#197]
I am running some tests on Notepad++ using FLAUI.UIA3
When I find one of the buttons in its toolbar by location. The name property look like it is filled correctly when the test application is running, but whenever I set a breakpoint in VS and inspect the AutomationElement when the debugger stops at the breakpoint, the Name property looks like its empty in the debugger preview. 

This happens only with some applications. Wordpad for example behaves correctly, it shows the Name fields correctly in both cases. It's Notepad++ that shows this issue (and probably others as well). Any ideas what is causing this?

**Comment by Roemer** [comment]
The problem is notepad++
A test shows that the toolbar buttons have no text by default. But if you hover over one of them with the mouse pointer, all of them have a name while you are hovering over them.
