### ISSUE TITLE
Exception in hello word example from README.md

### ISSUE THREAD

**Issue by bitbonk** [FlaUI/FlaUI#198]
This code from README.md

```
var app = Application.Launch("calc.exe");
using (var automation = new UIA3Automation())
{
    var window = app.GetMainWindow(automation);
    var button1 = window.FindFirstDescendant(cf => cf.ByText("1"))?.AsButton();
    button1?.Invoke();
}
```

fails with the following exception:

> Exception thrown: 'System.InvalidOperationException' in System.dll
> Additional information: Process has exited, so the requested information is not available.
>    at System.Diagnostics.Process.EnsureState(State state)
>    at System.Diagnostics.Process.get_MainWindowHandle()
>    at FlaUI.Core.Application.<WaitWhileMainHandleIsMissing>b__29_0()
>    at FlaUI.Core.Tools.Retry.While(Func`1 whilePredicate, TimeSpan timeout, Nullable`1 retryInterval)
>    at FlaUI.Core.Application.WaitWhileMainHandleIsMissing(Nullable`1 waitTimeout)
>    at FlaUI.Core.Application.GetMainWindow(AutomationBase automation, Nullable`1 waitTimeout)

The calculator is shown, so the process has not actually exited.

I am on Windows 10 Pro 1803. Using XUnit and the ReSharper unit test runner.

**Comment by Roemer** [comment]
This example works only on the pre-windows-store calculator. On windows 10, you should use the calculator example from the UI-test project in the code. Maybe I should create a different example or add a note to the example.

**Comment by bitbonk** [comment]
Yeah the hello word examples on the "welcome page" should work right off the bat.

**Comment by bitbonk** [comment]
Also: Why doesn't the calculator work. Isn't UIA3 supposed to work with UWP ?

**Comment by Roemer** [comment]
Look at the example in the test assembly. You need to start windows store apps differently as they run in kind of a host-process. The "calc.exe" from windows 10 is just some kind of launcher (so that all the people which use calc.exe for a long time still can start it) which lauches the calculator store app and then exits, that's why you get the `Process has exited` message ;)

**Comment by Roemer** [comment]
As there is a note about the issue, I will close this.
