### ISSUE TITLE
bring back automatic retry for all Find methods

### ISSUE THREAD

**Issue by bitbonk** [FlaUI/FlaUI#201]
I would like to pick up the discussion started [here ](https://github.com/Roemer/FlaUI/issues/190#issuecomment-412185961) again.

To me it seems very common that UI elements need to build up before the can be found using the `AutomationElement.FindXXX(...)` methods. If you have fairly a dynamic (and slow) UI, this can happen a lot and forces you to use `Retry` all over the place when finding the elements.

So I suggest that you can optionally enable and configure the retry behavior for all `AutomationElement.FindXXX(...)` methods in a block of code or in a test method.

This way we do not need to clutter our test code with a lot of `Retry`s.
Something like this did already exist in FlaUI 1.3 to some extend.

**Comment by harryhobson** [comment]
I really like `Retry`, but I also experience this problem. There are many situations where it is certain the element is going to appear, however it may take some time - and a large portion of code may be these 'certain' waits.

**Comment by atresnjo** [comment]
You could simply write an extension for AutomationElement where you can pass a retry delay and retry count.

**Comment by bitbonk** [comment]
@atresnjo I would have to mirror all the exisiting find methods as extension methods and add those paramters. I feel that they should be in FlaUI out of the box.

**Comment by Roemer** [comment]
I thought about adding a `Retry.Find` method.
The usage would look like:
```csharp
Retry.Find(() => window.FindFirstChild(cf => cf.ByControlType(ControlType.Window)),
    new RetrySettings
    {
        Timeout = TimeSpan.FromSeconds(6),
        Interval = TimeSpan.FromMilliseconds(500)
    }
);
```
So as you see, as first parameter, you pass any search method that returns an `AutomationElement` or `AutomationElement[]` and as second, an object with some retry settings.
What would you all think about that? Would that be sufficient for the usual needs? As an alternative, the `RetrySettings` could be added as parameters to all Find methods but that does seem less flexible to me.

**Comment by Roemer** [comment]
One more alternative would be to add an `UseRetry` scope.
Something like:
```csharp
using (var retryScope = new RetryScope(new RetrySettings ...)) {
    element.Find... // This now uses the retry
    element.Find... // This now uses the retry
}
element.Find... // This now does not use the retry
```

**Comment by Roemer** [comment]
I've actually added the Retry.Find methods. Feel free to check them out.
