### ISSUE TITLE
is there any way to block the specified form when using FromPoint()?

### ISSUE THREAD

**Issue by kuangshi00** [FlaUI/FlaUI#206]
Hi, I want to make a screenshot tool with FlaUI, but using FromPoint() to return the form of the screenshot tool, is there any way to block the specified form while using FromPoint()?

**Comment by Roemer** [comment]
You mean you want the element below the screenshot tool-form? There are some ways to make a window "click-thru" with win32. Not sure if UIA also works with this. But in general, there are tons of good screenshot tools. Just use one of them.
