### ISSUE TITLE
Tooltip Visiblity parameter missing

### ISSUE THREAD

**Issue by kevinheyvaert** [FlaUI/FlaUI#224]
Hello, 

Is there way to get the tooltip (in FlaUI the HelpText property of AutomationElement) visibilty? I already had tests that found the helptext but that the tooltip was not visible. I want to catch that during automated tests and not during manual. 

With kind regards,

Kevin

**Comment by Roemer** [comment]
The tooltip is a special think. It is like a dropdown, a window either directly on the desktop or on the root of the application. Best way to get the tooltip-window is to use FlauInspect and use the hover mode and try to catch the tooltip window when it is open. Then you know where it is and what title it has and then you can try to find that window and get the content to check if your tooltip is visible or not.
