### ISSUE TITLE
A generic error occurred in GDI+.

### ISSUE THREAD

**Issue by wxue1011** [FlaUI/FlaUI#242]
When I'm using "window.CaptureToFile(file)" an exception below is catched.

```
A generic error occurred in GDI+.   
at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams) 
at FlaUI.Core.CaptureImage.ToFile(String filePath)
```
Below is details.
1. I used a thread to capture file. When the thread is running, I do abort the thread.
2. Open the capture file's folder with explorer.exe. 
3. Run thread more once, the error occurred.(if step2 is none, the error didn't occur.)

I can't fix the problem.I appreciate your help. Thanks a lot.

**Comment by Houuse** [comment]
same error with diffrent situation

actually it's the same code from the docs
`            try
            {

                url = "https://stackoverflow.com/questions/12909905/saving-image-to-file";
                Url generator = new Url(url);
                string payload = generator.ToString();
                QRCodeGenerator qRCodeGenerator = new QRCodeGenerator();
                QRCodeData qRCodeData = qRCodeGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q);
                QRCode qRCode = new QRCode(qRCodeData);
                var qRCodeAsBitmap = qRCode.GetGraphic(20);
                qRCodeAsBitmap.Save($"C:\\Users\\Houuse\\Desktop\\{DateTime.Now}", ImageFormat.Jpeg);
                System.Diagnostics.Debug.WriteLine(qRCodeAsBitmap);

            }
            catch (Exception ex)
            {

                throw;
            }`

**Comment by Roemer** [comment]
@Jazzman82 Good catch. I think older .NET Framework Versions just threw that exception on an invalid path. Newer ones give `The given path's format is not supported.`.
@wxue1011 @Houuse Can anyone if you check that the path to save is a valid filename?

**Comment by Roemer** [comment]
Closed due to no answer. Feel free to re-open if it is still an issue.
