### ISSUE TITLE
Mouse is blinking quickly when recording video.

### ISSUE THREAD

**Issue by wxue1011** [FlaUI/FlaUI#246]
How to avoid mouse blinking?

Thanks a lot.

And another question.
CPU usage rate is always almost up to 100% when recording video.

**Comment by Roemer** [comment]
Do you have an example video?
The CPU is usually fairly high as video encoding needs to be done in the background. You can play around with the video format, fps and quality to make it use less cpu.

**Comment by wxue1011** [comment]
Thanks. maybe the reason is that it used much cpu.
