### ISSUE TITLE
Check if WinForms application is fully loaded

### ISSUE THREAD

**Issue by pavlikpatrycja** [FlaUI/FlaUI#248]
Hi, 
I am creating engine to automated tests for WinForms application using FlaUI library. I found interesting problem and have no idea how to solve it without using Thread.Sleep method. I wish I could avoid unnecessary delay in test execution because the engine works on many different computers, where the time of sleep can much differ. 
The thing is that when I start application process I wait for input idle to make sure that application is ready to work. Before engine tries to click some element it checks if this element is enabled and visible. The problem occures when element xpath uses indexing. Application window contains two elements of type Edit. Xpath of first one is Window/Edit[1], and the second Window/Edit[2]. Sometimes when test execution is very quickly it happens that two next clicks are performed on first element as if the other one was not loaded quickly enough in the application. When I changed xpaths of elements to use name attribute it seems to work properly but I would like to use indexing anyway. 
Is there any way to check if  all window elements of the external application are fully loaded ? 
Thanks in advance!

**Comment by Roemer** [comment]
Per se there is no default way to determine if the application is loaded. If possible, the application itself should provide a loading screen or loading spinner which is displayed until the application is fully loaded. You can then do a `Wait` with FlaUI until the loading screen or spinner is removed and then continue with the test.

**Comment by Roemer** [comment]
I'll close this as there is nothing to add from FlaUIs side.
