### ISSUE TITLE
Substitute of SearchCondition.ByClosestControl 

### ISSUE THREAD

**Issue by mlisowski** [FlaUI/FlaUI#252]
Hello,
I have small issue with navigating through WinForms application. 
Some of controls have AutomationID which is constant (e.g. like window title).
But other controls have changing automationID (it is number which changes after every application triggering).

And I have problem to identify few comboBoxes - unique identification properties (like automationID or handle) will change after application relanuch and test would throw exception. And I have not access to source code of App.

And this controls look following - there is textbox with name (e.g. Customer) and combobox with list of options (e.g. Coca-Cola).
________________________
[TextBox label]  [CombobBox]
________________________

Maybe do you know way to idenify this comboBox by pointing the clostest textBox?
Something like SearchCondition.ByClosestControl in Windows Automation ("Condition for finding the nearest element to the given UI control").

**Comment by yawnston** [comment]
If you have a reliable way of finding that TextBox, you can always get that TextBox's parent AutomationElement, and then find a way to find that ComboBox between the parent element's children. If you're lucky, it could be the only ComboBox among the children, but if it isn't, maybe there is some other distinguishing property (like the labels of selectable items or something similar).

So I might do something like this if the parent element has only one ComboBox child:

```cs
var textBox = ReliablyFindTextBox();
var parent = textBox.Parent;
var comboBox = parent.FindFirstChild(cf => cf.ByControlType(ControlType.ComboBox));
```

**Comment by mlisowski** [comment]
Thanks for response. But this method wasn't working - mentioned textbox is sibling to comboBox, not child or parent, and structure of window is very messy so it's almost impossible to identify these elements in such way.

I solved it by getting distance between found textbox and all found comboboxes (but tested only on Windows Automation yet, on FlaUi I will be able to test in few weeks after vacation). But if anyone is interested - it should work on FlaUi as well after few changes :) GetDistance method returns distance between two given points.

`public static ComboBox FindComboBoxByLabel(Window window, string label)
        {
            var comboBoxes = window.FindAllControls<ComboBox>();
            var description = window.FindControl<Text>(SearchCondition.ByName(label));

            var closestOne = comboBoxes.First();
            foreach (var comboBox in comboBoxes)
            {
                if (Utils.GetDistance(description.Center, comboBox.Center) < Utils.GetDistance(description.Center, closestOne.Center))
                {
                    closestOne = comboBox;
                }
            }

            return closestOne;
        `}``

**Comment by Roemer** [comment]
I think this is something very specific. Usually navigating with to parents and children should be enough to solve this issue. Alternatively, you could also try searching by XPath.
