### ISSUE TITLE
Windows form tree view

### ISSUE THREAD

**Issue by maoyuan456** [FlaUI/FlaUI#254]
When I use FlaUI testing for an windows form tool, it has a tree view control, and now I need select tree node 1 by 1 so could you please create a method to select all nodes in the future?

**Comment by Roemer** [comment]
What kind of tree view are you using? The default tree view only supports single selections as far as I know.

**Comment by Roemer** [comment]
Closed due to no answer. Feel free to re-open if it is still an issue.
