### ISSUE TITLE
Window.Move not working

### ISSUE THREAD

**Issue by ataliady** [FlaUI/FlaUI#267]
>             var app = Application.LaunchStoreApp("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
>             var automation = new UIA3Automation();
>             var window = app.GetMainWindow(automation);
>             window.Move(0, 0);

Calculator is successfully launched. I try to relocate the app window but the window.Move() just does nothing. Doesn't raise any error/exception either.

What am i missing?

**Comment by Roemer** [comment]
Windows store apps are a bit special.
Like in the calculator, the `container` window that can be moved is actually the parent of the main window.
The following should work:
```csharp
var app = Application.LaunchStoreApp("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
var automation = new UIA3Automation();
var window = app.GetMainWindow(automation).Parent.AsWindow();
window.Move(0, 0);
```

**Comment by ataliady** [comment]
Tried it, it worked for a few runs, but then i got the following issue:
`Window parent = window.Parent.AsWindow();`
While 'window.Parent' equals x, 'parent' is assigned as x.Parent (which in this case is desktop).

![windowParent](https://user-images.githubusercontent.com/19539503/68071295-cd63f780-fd81-11e9-9cc9-19c2fc24b258.PNG)

![parent](https://user-images.githubusercontent.com/19539503/68071301-d05ee800-fd81-11e9-86d9-8bb9da483563.PNG)

How can this be?
It's not constant though; sometimes 'parent' is assigned as desktop, and sometimes as calculator. Can't figure out how to deal with this.

**Comment by Roemer** [comment]
That is kind of strange. In the second case, would it work if you take the `window` instead of the parent?
So maybe first try to get the parent and if the parent is the desktop, do not use the parent, otherwise use the parent.
I know that WindowsStoreApps are quite special as they are usually running in (at least) one host process so it is not easy to get the correct process where the UI window resides.

**Comment by Roemer** [comment]
Closed due to no answer. Feel free to re-open if it is still an issue.
