### ISSUE TITLE
Create UniversalWindowApp test application

### ISSUE THREAD

**Issue by Roemer** [FlaUI/FlaUI#27]
Since they should be fully supported, should we add such an application?

**Comment by Portikus** [comment]
What about this topic? Is it possible to write tests for UWP apps? Would be very nice :)

**Comment by Roemer** [comment]
Yes it should be possible. This issue is just a note that there is no test UWP app in FlaUI itself.

**Comment by Portikus** [comment]
Ah ok. 
I will try to write some UI tests for UWP.
But anyway it would be very nice if there were an UWP testapplication.

**Comment by Roemer** [comment]
Feel free to create a small application (even when it only has a few simple controls) and create a PR for it.

**Comment by godrose** [comment]
@Roemer 
How do I launch a UWP App using the FlaUI library?
What path should I provide to `Application.Launch` method?

**Comment by Roemer** [comment]
See https://github.com/Roemer/FlaUI/blob/master/src/FlaUI.Core.UITests/CalculatorTests.cs
``` Application.LaunchStoreApp("Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");```

**Comment by godrose** [comment]
@Roemer Will check. Thanks!

**Comment by godrose** [comment]
@Roemer What about an application being developed? 
What is the proper way to start it as opposed to `.Launch(exePath)` in **WPF** ?

**Comment by godrose** [comment]
@Roemer Excellent job.
If I might recommend that you should add a short How-To as to the correct app Id to be supplied to the `LaunchStoreApp` method. It took me a while to figure out what exactly I should put there

**Comment by Roemer** [comment]
Probably won't happen anytime soon and there are now plenty of UWP apps in Windows that can be used for testing.
