### ISSUE TITLE
Add support for touch gesture

### ISSUE THREAD

**Issue by ilCosmico** [FlaUI/FlaUI#271]
It would be great to be able to test also touch events at all.

Any plan to add this in the future?

**Comment by Roemer** [comment]
Yes this is still planned. Any pre-analysis or even PRs are very welcome! It should basically just be a bunch of WinAPI methods/classes/constants that needs to be wrapped like for example in: https://stackoverflow.com/questions/10156400/injecttouchinput-windows-8-c-sharp-not-working-returns-false

**Comment by Roemer** [comment]
I just added touch support.
See https://github.com/FlaUI/FlaUI/wiki/Touch for the currently implemented (but not very carefully tested 😉) methods.
