### ISSUE TITLE
Caching AutomationElement

### ISSUE THREAD

**Issue by pm90pl** [FlaUI/FlaUI#273]
I'm not fully sure what is caching feature for. Can I interact with cached elements? Or it's only for purpose of accessing element property value? In the wiki there is mentioned an example of cache usage with grids. But grids aren't static - most grids in my app are using paging and any scroll can load more data.

Could someone provide a real world example of cache usage?

**Comment by Roemer** [comment]
Caching is rather specific. I have some information here: https://github.com/Roemer/FlaUI/wiki/Caching
Is that enough for your question? If not, what is missing?

**Comment by Roemer** [comment]
Generally you can interact with cached element in case they are still the current control that is displayed. This is usually less of the case of caching.
The usual case is that you have a search field and a grid showing the found results.
You would use the search normally and then, as soon as the grid is loaded, load that grid including children with caching.
Then you could navigate thru the grid and all child elements inside the cache without needing to send IPCs (Inter Process Calls) for each request.
If you use paging, you can load each page into the cache when it is needed and if you reload more data with scrolling, you can load each chunk that is loaded with the cached mode.
Caching is very specific and there are tons of pitfalls when using it. So I suggest only getting deeper into it if you have performance issues with the UI tests.

**Comment by Roemer** [comment]
I added some more information and another example to https://github.com/FlaUI/FlaUI/wiki/Caching. Hope this makes it more clear, otherwise re-open this issue.
