### ISSUE TITLE
Application.Attach() crashes in Logger.Default.Debug()

### ISSUE THREAD

**Issue by tetsushmz** [FlaUI/FlaUI#283]
Hi,

Just wanted to let you know that Application.Attach() crashes when the attached process is an x64 app and the test process runs in x86 mode. This is because accessing the Process.MainModule property in the Loger.Default.Debug() throws a Win32Exception (A 32-bit process is trying to access the modules of a 64-bit process.)

I like FlaUI very much. It works reliably. Thanks for creating this wonderful software!

Take care.

**Comment by Roemer** [comment]
Thanks for the information. I think I will remove that particular logging.

**Comment by Roemer** [comment]
I actually tried to get a fallback for that scenario (see ed852789584ab41dbe810b24de1c4819196f1654). Could you give it a try?

**Comment by tetsushmz** [comment]
I tested 3.0.0 (UIA2) in x64 mode. It worked well to the extent that my existing scenario tests can cover. Thanks for the fixes!
