### ISSUE TITLE
FlaUi Fails in Finding Descendant by Name for Wpf Apps

### ISSUE THREAD

**Issue by XingJordan** [FlaUI/FlaUI#286]
Hello,
I'm new to using FlaUi to automate my Ui tests.
I try to find the started App by Name property.
This fails WPF executables.

Here is the sample code which fails:

![grafik](https://user-images.githubusercontent.com/53291230/70451196-376c6c80-1aa5-11ea-83bc-39b3178b67f8.png)

The input to my function is as follows:
![grafik](https://user-images.githubusercontent.com/53291230/70451403-9b8f3080-1aa5-11ea-9ab8-0bd4748e3ceb.png)

So I try to get the AutomationElement by the name property.
In case of an WPF app with the name MainWindow the children property stays empty, i.e. no item was found.

Looking forward to your answers.

Best,
  Mathias

**Comment by XingJordan** [comment]
Here is the FlaUiInspect output
![grafik](https://user-images.githubusercontent.com/53291230/70451990-a9918100-1aa6-11ea-8af1-d931c83eaf48.png)

**Comment by Roemer** [comment]
In general, this works as expected.
I tried to run the following (in RoslynPad):
```csharp
#r "nuget:FlaUI.Core/3.0.0"
#r "nuget:FlaUI.UIA3/3.0.0"

using FlaUI.Core;
using FlaUI.Core.AutomationElements;
using FlaUI.Core.Conditions;
using FlaUI.UIA3;

var automation = new UIA3Automation();
var window = GetMainWindow(cf => cf.ByName("FlaUInspect v1.2.0"), FrameworkType.Wpf);
Console.WriteLine(window.Name);

public AutomationElement GetMainWindow(Func<ConditionFactory, ConditionBase> conditionFunc, FrameworkType fwType)
{
    var window = automation.GetDesktop();
    var children = window.FindAllDescendants(conditionFunc);
    var applicationWndow = children.FirstOrDefault(c => c.FrameworkType == fwType);
    return applicationWndow ?? throw new InvalidOperationException(nameof(applicationWndow));
}
```
while having FlaUInspect 1.2.0 open and this correctly finds the Window.

I see a few issues here:
1. You are using `FindAllDescendants` which looks thru absolutely all controls, which might be too many and it fails. You should probably just use `FindAllChildren` here as the window you want is a direct child of the desktop.
2. You are getting a list of elements and then further limit them with linq (FirstOrDefault). Why don't you directly add that criteria to the condition while Finding the elements? This would look like;
```csharp
cf => cf.ByName("FlaUInspect v1.2.0").And(cf.ByFrameworkId("WPF"))
```
This will be much faster as it directly finds the window you want.

On a side note, i just saw that I only take a string in `ByFrameworkId`, I will probably add a new method `ByFrameworkType` where you can directly pass the `FrameworkType` for easier use.

**Comment by XingJordan** [comment]
Hey, 
thanks for the fast answer.
Regarding your comments, I used linq because I was not aware of the fluent syntax you provided, will change that.
I used the descendants method because for other programs I need to access controls which are not direct child’s of the desktop. Shall I change my methodology to first find the main child and afterwards query child’s of the retrieved window. I can see a similar behavior in your inspect program. 

What is the limit for the descendants method? Here I have entries of about 6000 child windows.

**Comment by Roemer** [comment]
Yes, in general is it better to try to Find only as few controls as needed as the whole UIA stuff uses Inter Process Communication and such.
So whenever possible, perform multiple searches with few results (like first find a pane, then a table inside then search all children in the table to get all the rows).
I think there is no specific limit. What can be an issue if it takes too long to get the results between the border of different processes, then it might fail. You can adjust some COM timeouts to prevent this timeout but it is better to have multiple fast searches.

**Comment by Roemer** [comment]
I'll close this. If it is still an issue, feel free to reopen.
