### ISSUE TITLE
How to find an element by regex or pattern?

### ISSUE THREAD

**Issue by lanzorg** [FlaUI/FlaUI#291]
I would like to find a window element by name that matches a regex.
Is it possible with FlaUI?

```
var app = Application.Launch(...);
using (var automation = new UIA3Automation())
{
    var desktop = automation.GetDesktop();

    // Workaround for CLR/System.NullReferenceException.
    Retry.WhileNull<Window>(
        desktop.FindFirstChild(cf => cf.ByName("The window name is not always the same...")
    ).AsWindow);

    var window = desktop.FindFirstChild(cf => cf.ByName("The window name is not always the same...")).AsWindow();
    var button = window.FindFirstChild(cf => cf.ByText("Yes")).AsButton();
    button?.Invoke();
}
```

**Comment by Roemer** [comment]
There exists an `PropertyConditionFlags` wich you can use with `FindWithOptions` where you can at least match substrings. Regex is not possible in UIA, for that you need so search all elements of interest and manually do a regex search thru those items.

**Comment by lanzorg** [comment]
Thanks for the quick answer. :)

**Comment by mtnmayer** [comment]
> There exists an `PropertyConditionFlags` wich you can use with `FindWithOptions` where you can at least match substrings. Regex is not possible in UIA, for that you need so search all elements of interest and manually do a regex search thru those items.

do you have an example of how to use substrings?

**Comment by ThanhNg** [comment]
To anyone who's still looking for the answer in 2024: XPath doesn't support wildcards matching but it DOES support string expressions like: starts-with, ends-with, contains, substring... which may provide (almost) the same functionalities. For example:

-  Button[starts-with(@Name, 'P')] --> find buttons which Name starts with P
