### ISSUE TITLE
How to click on button from a Chrome based window?

### ISSUE THREAD

**Issue by lanzorg** [FlaUI/FlaUI#292]
I would like to click on the Start button with FlaUI but it seems inaccessible.
I tried finding by AutomationId, Name, ... without any success.
However, it's accessible from FlaUInspect when **I enable the Hover Mode only**.

![](https://framapic.org/2jEeWDiajZYB/JbLestiat4w3)

**Comment by lanzorg** [comment]
It works with pywinauto,.
So I probably did something wrong with FlaUI. ;)

```python
from pywinauto import Application

exe = "..."
app = Application(backend="uia").start(exe)
win = app.window(title_re="(9Hits)")
win.StartButton.click()
```

**Comment by Roemer** [comment]
Can you post the FlaUI code?

**Comment by lanzorg** [comment]
I tried many things without any success.
This is one of the not working code:

```cs
            var app = Application.Launch($"{this.InstallDirectory}\\9hviewer.exe");
            using (var automation = new UIA3Automation())
            {
                Thread.Sleep(8000);
                var window = app.GetMainWindow(automation);
                window.Focus();

                var buttons = window.FindAllChildren(
                    cf => cf.ByName("Start")
                );
            }
```

**Comment by Roemer** [comment]
Try searching for the descendants instead of children.

**Comment by lanzorg** [comment]
I should really read the source code before posting stupid issues. 🙄

Thanks!
