### ISSUE TITLE
Windows 10 starting desktop application error

### ISSUE THREAD

**Issue by pavlikpatrycja** [FlaUI/FlaUI#293]
Hello, 
I use FlaUI version 2.0.0-alpha6 to test WinForms application. Everything was fine until I started testing this application on Windows 10. I start app in this way:
![image](https://user-images.githubusercontent.com/14920046/70994729-23d98b00-20cf-11ea-9dc4-0d252a023d00.png)
The error I get is: 
![image](https://user-images.githubusercontent.com/14920046/70994774-3c49a580-20cf-11ea-9338-2222fdb0647d.png)
When I check the process id of started application in commandline it is different. First I faced problem testing calc.exe but found out that win32calc.exe works fine. I tried app.GetAllTopLevelWindows(automation)[0], app.GetMainWindow(automation) but it doesn't work as started application has exited. 
What is the correct way to start and attach to WinForms application using FlaUI under Win10? Thanks in advance for help.

**Comment by Roemer** [comment]
Is it a WinForms Application or a Windows Store Application? It might be that the exe you are starting is just some kind of shim which in the end starts the real executable and closes the shim. That is the same with calc.exe on windows server as you wrote above. Check if multiple processes are started when you start your application.
