### ISSUE TITLE
Fully qualified class name

### ISSUE THREAD

**Issue by bdb-stack** [FlaUI/FlaUI#294]
Is there any way to access the fully qualified class name from an Automation Element? For example, 'MyProject.MyModule.MyWPFControl' rather than just 'ComboBox'.  We have a number of custom controls that all appear with ClassName=ComboBox but need to be automated differently. It would be nice to have a generic method which can perform the necessary automation based on the fully qualified class names without needing to mess around with any AutomationProperties to determine which control we're dealing with. Or is there an alternative way to approach this problem? I have worked a bit with Squish, which does have this feature, so I'm assuming there is some method I can use here.

Thanks for your time,
-B

**Comment by Roemer** [comment]
Not directly. The `ClassName` is a .NET / WPF value, FlaUI only has access to what is exposed to `UIA`. What you can do in your WPF control is use a custom `AutomationPeer` and probably override the `GetClassNameCore` and return your class name there.

**Comment by Roemer** [comment]
Closing as a solution is proposed.
