### ISSUE TITLE
Issues finding windows in .NET Core app

### ISSUE THREAD

**Issue by fernandreu** [FlaUI/FlaUI#298]
I have a WPF application that multitargets .NET Framework 4.6.1 and .NET Core 3.0. I started adding UI tests via FlaUI.UIA3 (v3.0.0).

When using .NET Framework 4.6.1, I can use a code similar to the one in the documentation with no issues at all:

```csharp
using FlaUI.UIA3;

var app = FlaUI.Core.Application.Launch(exePath);
using (var automation = new UIA3Automation())
{
    var window = app.GetMainWindow(automation);
    ...
}
```

However, when using .NET Core 3.1, the same code will hang indefinitely (apparently) in the `GetMainWindow` call, even though I can see the main window displayed on my screen. Using the following workaround, I can successfully get the window in both runtimes:

```csharp
using FlaUI.UIA3;

var app = FlaUI.Core.Application.Launch(exePath);
app.WaitWhileMainHandleIsMissing(TimeSpan.FromSeconds(2)); // Or just Thread.Sleep(...)
using (var automation = new UIA3Automation())
{
    var window = app.GetAllTopLevelWindows(automation).First();
    ...
}
```

It seems the minimum time I need to wait is about 1 second; with less than that, the `GetAllTopLevelWindows` call might return an empty array. The same would happen if I substitute that call with:

```csharp
window = automation.GetDesktop().FindFirstChild(cf => cf.ByProcessId(app.ProcessId)).AsWindow()
```

Is there any specific configuration needed for .NET Core, or any specific wait method I could use instead of an arbitrary `TimeSpan`?

Just in case it is relevant: the UI test project is referencing the WPF one so that all binaries get copied in its bin folder. Then, I am obtaining the path to the executable from there. I also had to [add an MSBuild target](https://stackoverflow.com/a/58742265/1712861) so that the `.exe` can be launched as standalone from there. I think this part is set up correctly, as otherwise it wouldn't work with the extra timeout.

You can see the full project [here](https://github.com/fernandreu/office-ribbonx-editor), and the class where I am using FlaUI [here](https://github.com/fernandreu/office-ribbonx-editor/blob/master/tests/UITests/Helpers/AppManager.cs).

By the way, it's nice to see that FlaUI works in Azure Pipelines out of the box!

**Comment by NetMage** [comment]
I see a similar issue with .Net 4.8 using LINQPad 5 and .Net Core 3.1 using LINQPad 6 on Windows 10 version 1809.

**Comment by fernandreu** [comment]
I did a bit of digging and found out some odd things. I posted a [question](https://stackoverflow.com/questions/60342879/process-mainwindowhandle-is-non-zero-in-net-framework-but-zero-in-net-core-unl) in StackOverflow to see if somebody can help before I find out myself somehow.

I am convinced it is a generic issue occurring in .NET Core in general. If it turns out there is an easy fix for which the FlaUI code needs to be changed, I can make a pull request myself.

**Comment by fernandreu** [comment]
Just answering myself both here and in StackOverflow: there is an issue in .NET Core causing this. I submitted a pull request to fix it. I would suggest not making any changes to the FlaUI library and wait for the fix, as affected users should just be able to update the version of the `System.Diagnostic.Process` package whenever it comes out (or perhaps a minimum version can be enforced by the library).

In the meantime, the way I am going to fix this for my own app is by having a class derived from  copy of the `Application` class where, instead of using `_process.Refresh()`, it gets reassigned (so it cannot be a `readonly` field anymore). See [here](https://github.com/fernandreu/office-ribbonx-editor/blob/f09e54f109f2dcae2bc94a70db79b78088871810/tests/UITests/Helpers/Application.cs#L288).

Unfortunately, you cannot set `IsMainWindow = true` this way because it is an internal property. This just means that `Window.GetMainWindow()` will get re-evaluated even when called from the main window.

**Comment by mletterle** [comment]
Oddly, I got this issue with .NET 4.7.2... instead of copying the class, this little bit of hackery seemed to work around it:

```cs
application = Application.LaunchStoreApp(applicationPackageName);
var newApplication = Retry.WhileNull(() =>
{
    var ourProc = Process.GetProcessById(application.ProcessId);
    if (ourProc.MainWindowHandle != IntPtr.Zero)
    {
        return new Application(ourProc, true);
    }

    return null;
}, TimeSpan.FromSeconds(30), TimeSpan.FromMilliseconds(50)).Result;

var mainWindow = UIUtil.UIAutomation.FromHandle(newApplication.MainWindowHandle).AsWindow();

```
