### ISSUE TITLE
FlaUI with Windows Task Scheduler

### ISSUE THREAD

**Issue by santhosh-net** [FlaUI/FlaUI#300]
Hi,

I have a requirement like, I want to integrate FlaUI Test cases with Windows Task Scheduler.
I have done that. I am running my scripts using nunit-console.exe from batch mode.
Here the problem is, when i use "Run when the user is logged on" (Windows Task Scheduler option), Test cases are executing properly.
But when i choose "Run whether user is logged on or not" then test cases are failing. Stating that controls are not finding.

Please give me a solution.

**Comment by Roemer** [comment]
When there is no desktop session, there is no UI so obviously the tests fail. You almost always need a desktop session for UI tests. There are plenty of possibilities with auto-login and such methods to make sure there is a desktop session.

**Comment by santhosh44444** [comment]
can you please suggest me one Auto login way?

**Comment by Roemer** [comment]
See: https://support.microsoft.com/en-us/help/324737/how-to-turn-on-automatic-logon-in-windows

**Comment by santhosh44444** [comment]
i have tried this. but its not working...

**Comment by Roemer** [comment]
Please describe what you tried and what is not working.

**Comment by santhosh44444** [comment]
Windows account is Automatically not logging.

**Comment by rperneel** [comment]
do you have a welcome message on the windows machine that needs to be dismissed?  I have not been able to do the auto login if the domain that I am on has a welcome message.

**Comment by tomaustin700** [comment]
Yeah @rperneel is exactly right, welcome messages will break the auto logon. The way we get around this is having all our automation agents (vm's joined to the domain which run tests) in a separate OU and then have a group policy assigned to that OU to disable the welcome message.

**Comment by Roemer** [comment]
Closing this as there is nothing more I can do in FlaUI.
