### ISSUE TITLE
About Infragistics Controls

### ISSUE THREAD

**Issue by santhosh-net** [FlaUI/FlaUI#302]
Hi @Roemer 

We are using Infragistics controls in My Application, which are combination of WPF and Winfroms controls.
Could you please suggest me, how exactly I decide UIA2 or UIA3.

Thanks
Santhosh

**Comment by Roemer** [comment]
Inspect your application with FlaUInspect in UIA3 mode. Browse around and check if the it seems that all controls and values you need are visible. If things are not visible, switch to UIA2.
In general, UIA3 should always be preferred as this provides more features.

**Comment by santhosh44444** [comment]
@Roemer thank you.
I am able to find all the controls through UIA3 Pattern, 
This is a bit funny. 

I have a Combo box  control (UltraComboBox).
Under combo box, ListItem is there.
If I try to select Combobox item using **Select** method, it is raising an exception.
Should i write my own code to Select or any other way to do it?

**Comment by Roemer** [comment]
If the select of the selectionpattern fails, then there is probably a bug in the infragistics control. You can write them and in the mean time, use your own code to select the desired item.

**Comment by ponmudivn** [comment]
I cannot find infragistics grid elements in FlaUInspect.

**Comment by Roemer** [comment]
@ponmudivn Are you using the latest version of infragistics controls? Also make sure FlaUInspect runs with at least the same privileges as your application (or just run it as Admin).

**Comment by ponmudivn** [comment]
We are using Infragistics v1.52 and running FlaUInspect as system admin

**Comment by Roemer** [comment]
This is actually very old and not supported by infragistics anymore. Do you have a chance to try the latest version (trial) of the infragistics control?

**Comment by ponmudivn** [comment]
@Roemer I'm working on automating testing for legacy UI. Thanks for comments.

**Comment by Roemer** [comment]
Closed due to inactivity. Please re-open if you still have issues.
Also as old infragistics controls were used that do not support UIA, FlaUI cannot do anything.
