### ISSUE TITLE
FlaUI cannot see what is inside Teleriks RadTabControl  control

### ISSUE THREAD

**Issue by tomaszlachgc** [FlaUI/FlaUI#303]
Steps to reproduce:
1. Try to retrieve data from an control build using Telerik's RadTabControl e.g. from a datagrid inside the tab

Actual Result:
FlaUI does not see the element inside. 

Similar problems with this controls have been reported for CodedUI e.g. https://www.telerik.com/forums/radtabcontrol-additionalcontent-ui-automation-not-working

Unfortunately, I have no idea how to fix this in FlaUI.

**Comment by Roemer** [comment]
Could you provide me a very simple executable with a such a control in it?

**Comment by santhosh44444** [comment]
@Roemer I faced this situation, In my case-control was different, So i kept that control on AutomationElemnt, Then traversed to the child control in it. With Few lines of code, i did what i expected.

**Comment by tomaszlachgc** [comment]
It occured that the problem is caused by the fact that the data in the control is loaded dynamically. You just have to search for an element more than one time, to make it work.
