### ISSUE TITLE
How to automate UI testing of DevExpress grid using FlaUI

### ISSUE THREAD

**Issue by apoorv0012** [FlaUI/FlaUI#307]
I have a WPF appliation that has a DevExpress Grid. The Grid has a button on click on which a new row is added at the last. 
I want to edit that last row by inputting values in all or selected columns based on the column headers. How can I do that using FlaUI. 
Secondly, I want to edit any random row on the grid and edit only selected columns to check the validity as well. How can I achieve that?

**Comment by santhosh44444** [comment]
@apoorv0012 are you able to Find those Controls using FlaUI-Inspect?

**Comment by Roemer** [comment]
What did you try already? How does your grid and rows look in FlaUInspect?

**Comment by Roemer** [comment]
Closed due to inactivity. Please re-open if you still have issues.
