### ISSUE TITLE
Keep MainWindow snapshot of timestamp in variable

### ISSUE THREAD

**Issue by kevinheyvaert** [FlaUI/FlaUI#308]
Hello,

I have maybe a stupid question. But is it possible to get the current MainWindow of the application under test into a variable, do some actions and then perform checks on the snapshot of the main window in the variable? 

Im doing a kind of measurment in my application under test and I want to see of tabs and buttons are disabled during a measurement. But my measurement is really short and my check for disabled items takes already the whole measurement progress and I want to check also other stuff during a measurement. And I cannot control the duration of the measurement.

So is there an easy way to keep old MainWindow snapshots? Let me know what is possible or suggestions.

Regards

**Comment by Roemer** [comment]
Theoretically, you could use caching for that. Cache the main window with all descendants or whatever you need before, do your tests and then compare the cached version to the current version.

**Comment by kevinheyvaert** [comment]
@Roemer thanks for the quick reply. Any example code for caching somewhere?

Thanks

**Comment by Roemer** [comment]
Have a look at the wiki: https://github.com/FlaUI/FlaUI/wiki/Caching

**Comment by kevinheyvaert** [comment]
`var cacheRequest = new CacheRequest();
cacheRequest.TreeScope = TreeScope.Descendants;
cacheRequest.Add(AutomationElement.Automation.PropertyLibrary.Element.AutomationId);
cacheRequest.Add(AutomationElement.Automation.PropertyLibrary.Element.Name);
cacheRequest.Add(AutomationElement.Automation.PropertyLibrary.Element.IsEnabled);
using (cacheRequest.Activate())
{
	var elementCached = mainWindow.FindFirst(TreeScope.Element, new TrueCondition());
	Assert.IsFalse(elementCached.IsEnabled)
}`

This should work then? Or where do I add my element to cach?

**Comment by Roemer** [comment]
Yes this would save the current MainWindow and all descendants and their automationid, name and isenabled flag inside.
Yes you then need to use CachedChildren to navigate thru your elements, do not use "Find" inside the cache.
Are you trying to get the CachedChildren inside the using block?

**Comment by kevinheyvaert** [comment]
So im using the code that I previously mentioned in a method that will return the CachRequest object.

And then Im using the CachRequest object in a using and then look for the cached children in the MainWindow object but that stays empty. Is this the correct way?

**Comment by Roemer** [comment]
Is this still an issue? Yes, you should be able to use the `CachedChildren` property on your `elementCached` to navigate the children.

**Comment by Roemer** [comment]
No response so I guess this is solved. If not, feel free to re-open.
