### ISSUE TITLE
Issue in Entering Text in TextBox

### ISSUE THREAD

**Issue by RajathHcJain** [FlaUI/FlaUI#312]
Hi ,

I'm new to FlaUi.

I'm trying to automate window based application , while inspecting text box control type is coming as Pane. so we are unable to enter text inside the text box.

Can anyone help.

![image](https://user-images.githubusercontent.com/59274257/73632249-25f8a880-4681-11ea-8704-f72d3c30ffd0.png)

Regards,
Rajath.HC

**Comment by Roemer** [comment]
That does not look too good. It seems that the controls your Windows Application uses does not correctly support Microsofts UIA Framework (which FlaUI uses). Do you know what controls that or? Java SWT? You can use workarounds with the `Mouse` and `Keyboard` class to interact with elements or enter  text.

**Comment by RajathHcJain** [comment]
Hi @Roemer ,

Thanks for the reply.
I have tried using 
mainwindow.FindFirstDescendant(cf.ByText("Name:")).AsTextBox().Enter("value");
But didn't workout.

Thanks,
Rajath.HC

**Comment by Roemer** [comment]
The textbox in your screenshot above does not have the text `Name:` but it has at least an automation id. You could try searching by that.

**Comment by Roemer** [comment]
Closed due to inactivity. Please re-open if you still have issues.
