### ISSUE TITLE
Capture window without drop shadow on Windows 10

### ISSUE THREAD

**Issue by juavol** [FlaUI/FlaUI#313]
When capturing a screenshot of a window (e.g. using CaptureToFile() or Capture(), etc.), the resulting image includes some pixels around the actual window, which appears to reflect the shadow including the background shining through. This happens at least my WPF application on Windows 10. 

Is there a way to exclude the shadow from the screenshot?

**Comment by Roemer** [comment]
Technically the border is part of the window so it is added.
What you can do is just shrink the capturing rectangle by the width of the border. You just need to find the correct value of the border by try/error.
```
var rect = element.BoundingRectangle;
var borderSize = 10;
var captureRectangle = new Rectangle(rect.X, rect.Y, rect.Width - borderSize, rect.Height - borderSize);
Capture.Rectangle(captureRectangle);
```

**Comment by Roemer** [comment]
I'll close this as there is a viable workaround. If you have something to add. Feel free to re-open the issue.
