### ISSUE TITLE
Using statement does not close application

### ISSUE THREAD

**Issue by nathanpovo** [FlaUI/FlaUI#316]
The [Application wiki](../wiki/Application) mentions that

> When the application object is disposed, the application itself is closed as well.

However, when an application is launched with the following code:

```csharp
using FlaUI.Core;
using FlaUI.Core.AutomationElements;
using FlaUI.UIA3;

namespace SystemTests
{
    public class AppDisposalTest
    {
        public void WhenAppIsDisposed_ShouldCloseApp()
        {
            using (Application application = Application.Launch("MyProgram.exe"))
            using (AutomationBase automation = new UIA3Automation())
            {
                application.WaitWhileMainHandleIsMissing();
                Window window = application.GetMainWindow(automation);

                // code to interact with the UI
            }
        }
    }
}
```

the application remains open.

**Comment by santhosh44444** [comment]
Application.Launch("MyProgram.exe")), it will launch the application, A new process will be started.
It remains open until you close it :)

**Comment by nathanpovo** [comment]
That is the current behaviour. 

However, the wiki mentions that when the `Application`object is disposed, such as by using 

```csharp
using (Application application = Application.Launch("MyProgram.exe"))
{
    // code to interact with the UI
}
```

or 


```csharp
Application application = Application.Launch("MyProgram.exe");

// code to interact with the UI

application.Dispose();
```

the `Application` object should close.

Looking at the `Dispose` method of `Application.cs` you can see that it doesn't actually do anything to close the application.

https://github.com/FlaUI/FlaUI/blob/5681531af173ac7312c596ff2eb5b0af870f9b46/src/FlaUI.Core/Application.cs#L128-L151

**Comment by Roemer** [comment]
This is on purpose.
When you do a lot of tests, each test probably gets a new instance of `Application`. In many cases, you want to keep it open accross tests (because it can have a huge loading time). So you decide on your own: Keep it open or close it on your own so it re-opens for the next test.

**Comment by nathanpovo** [comment]
That makes sense.

However, what resources does the `Dispose` method release?

In the scenario you described, couldn't one simply call the `Dispose` method in the test class teardown?

**Comment by Roemer** [comment]
It disposes the process object. What if you have multiple test-fixtures and want to keep the app open during all of them? I thought it is easier that you just call `app.Close()` whenever you want to close it. It would also be possible to add a flag like `AutoClose` or `CloseOnDispose` but I'm not sure if that is really needed.
