### ISSUE TITLE
Unable to locate second window of the app

### ISSUE THREAD

**Issue by godrose** [FlaUI/FlaUI#319]
Repro steps:

1. Create a simple WPF App
2. Open a window inside the main view code-behind/view-model/whatever 
3. Try to access this window (it has its own automation id and title)

Expected: the window is found amongst `GetAllTopLevelWindows` return value
Actual: the window is missing from `GetAllTopLevelWindows` return value

Note: This functionality exists in `TestStack.White`. I'm currently migrating the existing code.

**Comment by Roemer** [comment]
This window is probably a child of the main window. Did you check that?

**Comment by godrose** [comment]
> This window is probably a child of the main window. Did you check that?

Thanks. That was unclear.
Do you have also some kind of inspector/spy (Snoop style) which helps locating elements in `FlaUI` terms?

**Comment by Roemer** [comment]
Any inspect tool. I have also one which is FlauInspect.
