### ISSUE TITLE
How get Child control elements of "ToolBar Windows" use FromPoint function?

### ISSUE THREAD

**Issue by darkhelmet72** [FlaUI/FlaUI#326]
If you try to get "AutomationElement" when clicked on "Windows TaskBar" using "UIA3Automation.FromPoint()", the "FlaUi" returns different values, either "ToolBar" or "Pane" or "Button". How can you get all child "ToolBar" controls?

**Comment by Roemer** [comment]
Can you show in FlaUInspect/Inspect what exactly you want to get and what you get?

**Comment by Roemer** [comment]
I'll close this due to inactivity. Please re-open if you have more information.
