### ISSUE TITLE
FindFirstByXPath - don`t works! =((((

### ISSUE THREAD

**Issue by darkhelmet72** [FlaUI/FlaUI#327]
FindFirstByXPath-works every other time! = (((((This sucks! The method is completely unstable! Out of 10 app launches, 3-4 doesn't get an element by FindFirstByXPath! I don't know why! =(((

**Comment by Roemer** [comment]
Any more information here? Like how the xpath looks like and how the application looks in Inspect/FlaUInspect

**Comment by Roemer** [comment]
I'll close this due to inactivity. Please re-open if you have more information.
