### ISSUE TITLE
Can not get the name of tree. 

### ISSUE THREAD

**Issue by wxue1011** [FlaUI/FlaUI#329]
Hi,
I tried get the name of a tree, but it always returns empty string.
I also used FlaUInspect to hover the tree, the name of tree also is empty.
Thanks a lot.

**Comment by Roemer** [comment]
What name? WPF or Winforms or something else? A tree in UI has no text/name, only the nodes.

**Comment by wxue1011** [comment]
It's 64bit Winforms application.
Yes, i also think that tree has no name. 
Finally I got the reason.
FlaUInspect took the treeItem as a tree. when i use UISpy to get the element, the element type is treeitem. 
This appliction also has 32bit version that FlaUInspect did not take the target elemet as tree, it returns right type treeitem.

![FlaUInspect](https://user-images.githubusercontent.com/16728942/79625942-16a4d980-815f-11ea-8b91-02c7f039cf88.PNG)
![UISpy](https://user-images.githubusercontent.com/16728942/79625935-0a208100-815f-11ea-924d-40011dd7b78e.PNG)

I'm really sorry with my bad English. Appreciate much for your answer.

**Comment by Roemer** [comment]
Also keep in mind that UISpy uses UIA2, so you might also try that especially as you are on a WinForms application. If you still got problems, feel free to re-open this issue.
