### ISSUE TITLE
Color of element

### ISSUE THREAD

**Issue by placle** [FlaUI/FlaUI#330]
Hi, 
can you please help me with this? I have text box with red borders and one with blue. Can I somehow get the colors and tell witch one is red? 

Thank you!

**Comment by kevinheyvaert** [comment]
Correct me if im wrong, but borders are not native supported by UIAutomation. I dont see any automation pattern where the color could be. You need to make your own custom textbox (inherited from your textbox) and then give the color with a pattern (like the Value pattern)

**Comment by placle** [comment]
I figured it out :) I just needed make sure there is some red colour so I get it with Capturing element and then on the bitmap I used Getpixel :) 
Thank you!
