### ISSUE TITLE
FlaUI.Core.Input.Mouse.MoveTo throws exception.

### ISSUE THREAD

**Issue by wxue1011** [FlaUI/FlaUI#331]
Hi, when i used FlaUI.Core.Input.Mouse.MoveTo(v3.0.0) it sometimes throws exception above.
The same code in v3.0.0-rc.1 it did not happened.

Information:TimeSpan は、浮動小数点の数字でない値を受け入れません。   場所 System.TimeSpan.Interval(Double value, Int32 scale)
   場所 FlaUI.Core.Input.Mouse.MoveTo(Int32 newX, Int32 newY)

Information:期間が長すぎるため、TimeSpan がオーバーフローしました。   場所 System.TimeSpan.Interval(Double value, Int32 scale)
   場所 FlaUI.Core.Input.Mouse.MoveTo(Int32 newX, Int32 newY)

**Comment by ChetanJB** [comment]
Faced same exception for a button click automation with true as parameter to Click method.
Following is the exception message and exception stack 
Message: TimeSpan does not accept floating point Not-a-Number values.
at System.TimeSpan.Interval(Double value, Int32 scale)
   at FlaUI.Core.Input.Mouse.MoveTo(Int32 newX, Int32 newY)
   at FlaUI.Core.Input.Mouse.MoveTo(Point newPosition)
   at FlaUI.Core.AutomationElements.AutomationElement.PerformMouseAction(Boolean moveMouse, Action action)
   at FlaUI.Core.AutomationElements.AutomationElement.Click(Boolean moveMouse)

**Comment by kevinheyvaert** [comment]
I have also found the same issue in V3.0.0 when you use this method but the mouse is on roughly the same location where you want to move to.

**Comment by Roemer** [comment]
This should be fixed in the development version. I'll try to release it this week.

**Comment by Roemer** [comment]
3.1.0 is out, try that version. If it still fails, please re-open this issue or create a new issue.
