### ISSUE TITLE
Anyone using FlaUI with apps such as Putty?

### ISSUE THREAD

**Issue by geovaneo** [FlaUI/FlaUI#334]
I need to connect on remote server such as Linux/AIX using terminal apps such as Putty. I would like to get the content that is visible on screen. Putty has an option to copy all content to Clipboard, but I was wondering if I face any other clients.

Apps like that do not show the main content as an Automation element.

Any clues?

**Comment by Roemer** [comment]
Why would you automate an application like Putty that has an excellent command line interface to interact with the application? It is far easier and faster to just use the Putty CLI commands for that.

**Comment by geovaneo** [comment]
Hi @Roemer , I used Putty as a example since it is the more popular of its type. But there are other tools such as Putty(with no CLI) used to access legacy applications on AIX for example. I was wondering if I could automate data extraction from this applications, so I was trying with FlaUI. However I was not able to figure out a way of getting the Terminal results. Specifically in PUTTY, there is an option to copy everything to clipboard, but other tools do not have it.
Anyway thanks for your reply.

**Comment by Roemer** [comment]
I still don't see why you do not use the CLI. Anyway, you could use the mouse to open the menu (by clicking on the top left on the menu bar on putty) and then on the menu invoke the "Copy all to Clipboard"

**Comment by Roemer** [comment]
Most terminals do not provide any UIA wrapper as this does not make a lot of sense. Best you could to is to use keyboard shortcuts or the menu on top with the mouse input to copy the value to the clipboard and paste it. Or take a screenshot and use an OCR to convert the image to text. But as said before. Terminals should be controlled via CLI.
