### ISSUE TITLE
Moving from Teststack White to FlaUI

### ISSUE THREAD

**Issue by Harpreet20** [FlaUI/FlaUI#335]
Hi There

I have a big project written in Teststack white. Is there any efficient way of moving from TestStack white to FlaUI? We have approx. 200 tests under 3 projects. We have updated to .Net 4.8 and it broke all our UI tests written using TestStack.White. Please guide me if there is any best possible way.

**Comment by godrose** [comment]
@Harpreet20 In general it would depend on the exact functionality you use in the framework. I did something similar and it becomes very technical. As a rule of thumb use page object pattern if you haven’t used it yet. In my experience this makes upgrading smoother.

**Comment by Harpreet20** [comment]
Thank you Godrose
We have all the windows objects in one class. Could you please share your steps? is it more efficient to update the white framework code locally and enhance it OR migrate the tests to FlaUI. Are you using FlaUI to run tests on server/VM using build pipelines?

**Comment by godrose** [comment]
I would recommend migrating the tests to FlaUI. The APIs are somewhat similar but still it's faster in my experience. You can also migrate gradually and maintain them side-by-side.
I use FlaUI in a CI server as well using YAML.

**Comment by Roemer** [comment]
There is also a small adapter found here: https://github.com/FlaUI/FlaUI.Adapter.White

It allows to re-use some syntax from White but run with FlaUI. You could have a look at it.

**Comment by Roemer** [comment]
If you have more to discuss, please head over to the gitter chat.

**Comment by Logesh8008** [comment]
> There is also a small adapter found here: https://github.com/FlaUI/FlaUI.Adapter.White
> 
> It allows to re-use some syntax from White but run with FlaUI. You could have a look at it.



> There is also a small adapter found here: https://github.com/FlaUI/FlaUI.Adapter.White
> 
> It allows to re-use some syntax from White but run with FlaUI. You could have a look at it.



> There is also a small adapter found here: https://github.com/FlaUI/FlaUI.Adapter.White
> 
> It allows to re-use some syntax from White but run with FlaUI. You could have a look at it.

Hi @Roemer - Is white adapter still active? we have similar problem statement. ie. we need to migrate a test suite that is developed using white framework to FlaUI. We are getting some errors during the migration process. Especially some of the methods such as Application.Session(), WindowsFactory.Desktop, AutomationElement.ControlTypeProperty are not recognised. Would you be able to help with this?

**Comment by Logesh8008** [comment]
> Hi There
> 
> I have a big project written in Teststack white. Is there any efficient way of moving from TestStack white to FlaUI? We have approx. 200 tests under 3 projects. We have updated to .Net 4.8 and it broke all our UI tests written using TestStack.White. Please guide me if there is any best possible way.

Hi @Harpreet20 - Did you managed to resolve this problem? If so, can you please guide us with the steps. We are trying to use white adapter but getting some errors.

**Comment by Harpreet20** [comment]
@Logesh8008 
Hi Logesh, We moved to another solution and did not look at this thread. Did you manage to solve this problem? How was the merge?
