### ISSUE TITLE
Application.Close() - add flexibility to timeout and kill

### ISSUE THREAD

**Issue by qamil95** [FlaUI/FlaUI#338]
Hi!

Current implementation of Application.Close() calls CloseMainWindow() on _process and waits 5 seconds. After this, if process has not exited, it kills it and waits next 5 seconds. Could you add some flexibility to this timeout of waiting, and give an option to decide if process should be killed after Close? Current implementation makes it not useful when closing of application takes more than 5 seconds. Also, I wanted to take screenshot if close of application fails for any reason, but it's not possible when using Close() method because it is killed after trying no close. To keep backward compatibility, the easiest solution seems to be adding bool parameter killIfCloseFails with default value true, and wrap _process.Kill() with it. Other possibility is to use UIAutomation events instead of waiting, but it's longer story.

Regards,

Kamil

**Comment by Roemer** [comment]
I like that idea.

Check if https://github.com/FlaUI/FlaUI/commit/4f1b33173e8bbde3c7ac47af3621038053929104 would fix that for you. Then you can increase the timeout to wait, skip killing and with the return value of `false` you can take a screenshot and kill it yourself.

**Comment by Roemer** [comment]
Try with the new version 3.1.0. If you need more, reopen this issue or create a new one :)
