### ISSUE TITLE
Mouse.Scroll() does not work with negative values

### ISSUE THREAD

**Issue by kevinheyvaert** [FlaUI/FlaUI#339]
Hello, im using FLaUI to perform some mouse movements. I use the following code to scroll wit the mouse on a element which can zoom. if lines == 100, I can see it zoom in. But if I add -100, I want to zoom out but that does not work. Also I dont see any unit tests for this? Can this be a bug?
```csharp
try
{
    Keyboard.Press(FlaUI.Core.WindowsAPI.VirtualKeyShort.CONTROL);
    Mouse.Scroll(lines);
}
finally
{
    Keyboard.Release(FlaUI.Core.WindowsAPI.VirtualKeyShort.CONTROL);
}
```

**Comment by Roemer** [comment]
I added a small test with Notepad and it does scroll upwars and downwards. I also tried with chrome to zoom in and out and both work perfectly.
Keep in mind that you need to add a small delay (for example with `Wait.UntilInputIsProcessed`) on keybord or mouse input to make sure that the message got processed.

**Comment by kevinheyvaert** [comment]
I tried some different values and when using low number for the lines parameter I saw it scrolling back up. Seems to be only specific for my application under test. This is an issue from my side and this issue can be closed. Thanks for the response
