### ISSUE TITLE
fails to find the control if the UI is not in focus

### ISSUE THREAD

**Issue by Vasanthi30** [FlaUI/FlaUI#341]
I am attempting to automate windows application. I use the following command to find the controls
`var element = window.FindFirstDescendant(cf => cf.ByText(identifier));`
the below code am using to attach my application process by name.
```csharp
var automation = new UIA3Automation();
_process = Process.GetProcesses();
automation.GetDesktop();
foreach (var itemProcess in _process)
{
	if (itemProcess.MainWindowTitle == "Reconciliations")
	{
		app = new Application(itemProcess);
		break;
	}
}
```
It works fine when the page is in focus but fails to find the control if the page is minimized, behind another window, or not the current tab.

Thanks for your help

**Comment by santhosh-net** [comment]
FlaUI requires Active Window. It should be opened..

**Comment by Vasanthi30** [comment]
the application is opened but -- It works fine when the page is in focus
 but fails to find the control if the page is minimized, behind another window. is there way that flaui works even the active application is minimized?

**Comment by santhosh-net** [comment]
Minimizing the window, is that your requirement? 
Or Any Model Window popping up on your required window?

Thing is.. If the control is not not in visible state (Active State) then "No". You cant.
Switch back to the Window, then it works, I guess.

I have couple of TestStack.White and FlaUI Automation Test Cases, I running with the same problem,.

**Comment by Roemer** [comment]
If the window is minimized, there are several problems:
- The mouse cannot be used as it cannot click anywhere.
- Depending on the application, elements might be removed from display or even removed entirely when the window is not shown.
- The application might block any input if the window is minimized.

The same things can happen if the window is in the background. It is usually the best if the application to automate is in the foreground.

**Comment by Vasanthi30** [comment]
yes my requirement to minimize the window, and if i run the tests it should work though the window is minimized.

**Comment by Vasanthi30** [comment]
ok thanks. it would be good if we have that option , is this same behavior, if we run the tests on remote machine , the remote window as background ..  will it works?

**Comment by Roemer** [comment]
FlaUI has no control on how the application behaves when it is in the background or minimized. So if it works that's good, if not, FlaUI cannot do anything. Best is to always have the application in the foreground.
