### ISSUE TITLE
Reading properites from Pane

### ISSUE THREAD

**Issue by githubaja** [FlaUI/FlaUI#342]
There is a pane in my app and I need to read the Name property from it. Howver, Automation class doesn't have a "AsPane" method. Is there a workaround to get the Name property from a pane?

**Comment by Roemer** [comment]
Please post a screenshot showing the pane in FlaUInspect / Inspect.

**Comment by githubaja** [comment]
No problem, here it is (sorry for the obfuscation, some data are sensitive information)
![image](https://user-images.githubusercontent.com/55830353/82423727-7c4cf400-9a84-11ea-9fbd-4376f0645aed.png)

Part of the problem is that the main app, in the screen shot labeled as "Main form" (bottom arrow) launches a separate window, a text editor. So, I need to switch to that window and grab the Name property of the pane (pane is marked with top arrow).

Whatever additional info you need, just let me know.

**Comment by Roemer** [comment]
You can find additional windows which are not children of your main window if you use `automation.Gesktop()` and search for your window there (eg. with the name and/or process id).
A pane is just a plain `AutomationElement` so you don't need to convert it to anything else (`As...` method). You can then just use the `Name` property to get the text you want.

**Comment by githubaja** [comment]
I also tried application.GetAllTopLevelWindows(automation), it returns only the main windows of the app.
I'll try automation.GetDesktiop(), there's a lot of properties in it....I'll try to find active windows.

**Comment by Roemer** [comment]
The desktop is also just an automation element. So there you can just do a FindFirst with your conditions to find the window you need.

**Comment by Roemer** [comment]
Is this issue solved?

**Comment by githubaja** [comment]
It is. Thank you.
