### ISSUE TITLE
FlaUI.TestUtilities 0.1.0 does not work with FlaUI.Core 3.1.0

### ISSUE THREAD

**Issue by HavenDV** [FlaUI/FlaUI#343]
You need to update the package version to use the latest current version

**Comment by HavenDV** [comment]
I also offer versioning the same as for the main components - 3.0.0, 3.1.0

**Comment by Roemer** [comment]
I just released 3.2.0 and the Test-Utilities are now in-line with FlaUIs version so it should work from now on.
