### ISSUE TITLE
How do I get main window of an element?

### ISSUE THREAD

**Issue by koder217** [FlaUI/FlaUI#348]
I am grabbing an element using mouse position, now I want to know the main window parent of the element. What is the best way to accomplish this?

Currently, I am using a recursive loop and checking element.Parent for Desktop. if it is Desktop then the current one should be the main window. But for MS WORD, I get not supported error with e.Parent.Name. 

Here's what I tried: Is there a better way to do this?

```
      public static Window GetMainWindow(AutomationElement e)
        {
            string parentName = string.Empty;
            try
            {
                parentName = e.Parent.Name;
            }
            catch (Exception ex)
            { 
                System.Diagnostics.Debug.WriteLine("Exception in GetMainWindow -- " + ex.ToString());
            }
            if (parentName.Contains("Desktop", StringComparison.OrdinalIgnoreCase))
            {
                return e.AsWindow();
            }
            else
            {
                return GetMainWindow(e.Parent);
            }
        }
```

**Comment by Roemer** [comment]
You can use the `Properties` as they have an `IsSupported` flag or even an `ValueOrDefault` which returns the default if the property is not supported. So you could just use `e.parent.Properties.Name.ValueOrDefault`.
A totally different way would be to get the processid of your element and search the desktop for a window with the same processid. Depending on your application (and if you have multiple windows on the desktop with this application), this might be not always correct but maybe worth a try.

**Comment by koder217** [comment]
I will try the process id approach. Thank you!

**Comment by Roemer** [comment]
Is this issue solved?

**Comment by koder217** [comment]
Yes, sorry i forgot to close the issue.

Thank you!
