### ISSUE TITLE
Get contents of DataGrid from DevExpress

### ISSUE THREAD

**Issue by Valdiralita** [FlaUI/FlaUI#355]
Hello,

Im using the DataGrid from DevExpress and I would like to read from and write to the cells.
At the moment the Cells contain Text and Checkboxes, but when inspecting with FlaUInspect the elements are just listed as "custom" type.

![1](https://user-images.githubusercontent.com/1066165/84922605-5e47d300-b0c6-11ea-8d63-3c0c999c83e9.png)

This is what I have tried to access the checkboxes:
`dataItem.FindFirstChild("IsSelected").FindFirst(TreeScope.Descendants, new ConditionFactory(new UIA3PropertyLibrary()).ByControlType(ControlType.CheckBox))` returns null

`tableItem.FindFirstChild("IsSelected").FindAllDescendants()[0].AsCheckBox()` returns a CheckBox but accessing IsChecked throws System.InvalidOperationException: 'Native pattern is null'

I have been able to toggle the checkbox using `tableItem.FindFirstChild("IsSelected").Click()` which is unfortunately not suited for my usecase because i would like to check the current state or explicitly set it to true or false.

What would you suggest in that case?

regards

**Comment by Roemer** [comment]
Fid you enable `ClearAutomationEventsHelper.IsEnabled = false;` as stated in the https://github.com/FlaUI/FlaUI/wiki/Common-Issues`?

**Comment by Valdiralita** [comment]
Yes, I have set the `ClearAutomationEventsHelper.IsEnabled = false;` in the OnStartup(StartupEventArgs e) in App.xaml.cs.

When i use FlaUInspect with the `CTRL` selection function it just crashes at random locations with HRESULT: 0x80040201 An event was unable to invoke any of the subscribers. Though sometimes it manages to display that the element `Custom "" ""` has a CheckBox as a child.
That happens for example in MainViewModel.cs ElementToSelectChanged:
![grafik](https://user-images.githubusercontent.com/1066165/88657987-0b086d80-d0d3-11ea-85c4-ec4540e0108c.png)

Though sometimes it manages to display that the element `Custom "" ""` has a CheckBox as a child when i click into the checkbox fast while holding ctrl.
![grafik](https://user-images.githubusercontent.com/1066165/88658393-a699de00-d0d3-11ea-9e42-af56428ab184.png)


Searching in the code it looks like i can only find the `Custom "" ""`
![grafik](https://user-images.githubusercontent.com/1066165/88652552-499a2a00-d0cb-11ea-9ba4-945eae5c71a2.png)

**Comment by Valdiralita** [comment]
I was able to use the Grid pattern and get the value by specifying row and column. I had to implement my own grid to get non localized values for the checkboxes.

**Comment by Roemer** [comment]
👍
