### ISSUE TITLE
Element is offscreen but property IsOffscreen is false

### ISSUE THREAD

**Issue by Valdiralita** [FlaUI/FlaUI#357]
I have an element inside a scrollview. element.GetClickablePoint() gives me a Y value of >2500 which is well outside of my screen.
In this case IsOffscreen will always return false.

**Comment by Roemer** [comment]
Well `IsOffscreen` is something that the control provides. The elements in the scrollview probably show `IsOffscreen` as false even thou they are outside the windows bounds.
I acutally did a small test with a control like:
```csharp
<ScrollViewer>
    <StackPanel>
        <Button Height="100">Button1</Button>
        <Button Height="100">Button2</Button>
        <Button Height="100">Button3</Button>
        <Button Height="100">Button4</Button>
        <Button Height="100">Button5</Button>
    </StackPanel>
</ScrollViewer>
```
All the buttons always show `IsOffscreen` as `false` even when they are outside the scrollviewer (on top or bottom). This seems to be a feature or a bug in the `ScrollViewer`. I suggest that you check the `BoundingRectangle` of your control agains the `BoundingRectangle` of the ScrollViewer and if it is outside,
This can be done like this:
```csharp
var scrollBoundingRect = scroll.BoundingRectangle;
var elementBoundingRect = myElement.BoundingRectangle;
var isFullyVisible = scrollBoundingRect.Contains(myElement.BoundingRectangle);
var is partiallyVisible = scrollBoundingRect.IntersectsWith(myElement.BoundingRectangle);
```

You can use one of the `is...Visible` either if you want the element to be fully visible or also only partially.

Does that solve your issue?

**Comment by Valdiralita** [comment]
Yes that works, thanks! It's a shame that there can't be one function to determine if the control is visible on the screen. Now I have to be aware where the control is used to check if its visible.

**Comment by Roemer** [comment]
Problem is solved.
