### ISSUE TITLE
Access content from Chrome Legacy Window

### ISSUE THREAD

**Issue by lupusilviu** [FlaUI/FlaUI#362]
Hello,

I am trying to use this library, to get the content of a page, loaded inside a CefSharp component.
See this link for the exact use case: https://stackoverflow.com/questions/57890068/automation-for-chrome-legacy-window-chromium-using-winium

The problem is, as described there also, I cannot get to the controls inside the "Chrome Legacy Window". It gets this AutomationElement, but cannot go inside it. Is there any way of getting controls from inside this type of control?

Thank you.

**Comment by Roemer** [comment]
How dows the Chrome Legacy Window look in an inspect tool (like FlaUInspect)? Do you see content in there?

**Comment by lupusilviu** [comment]
Hello,

This is what it shows:
![Capture1](https://user-images.githubusercontent.com/59566205/88258285-795ec180-ccc8-11ea-9369-954088565085.PNG)
![Capture2](https://user-images.githubusercontent.com/59566205/88258286-7a8fee80-ccc8-11ea-85ea-87d56a8292d0.PNG)

**Comment by Roemer** [comment]
You could give UIA3 a try. But if the Chrome Legacy Window does not expose anything to UIA, there's nothing FlaUI can do except working with mouse/keyboard/screenshots. Also as far as I remember, to automate Chrome with UIA, accessibility needs to be activated in Chrome itself, maybe it is somehow the same with the Chrome Legacy Window.

**Comment by lupusilviu** [comment]
UIA3 did not do the trick either. Thank you for the suggesting FlaUInspect.

**Comment by Roemer** [comment]
Can you provide me a sample application with that Chrome Legacy Window?

**Comment by lupusilviu** [comment]
I was able to fix this, by forcing Cef Sharp (Chromium) to start with accessibility on:
cefSettings.CefCommandLineArgs.Add("force-renderer-accessibility", "true");

Seem something on that PC, did not tell the browser to expose Accessiblity. But giving it that param at startup, fixed it.

**Comment by Roemer** [comment]
Great that you figured out and many thanks for the feedback!
