### ISSUE TITLE
How to get Property Change update when IsOffScreen changes

### ISSUE THREAD

**Issue by lupusilviu** [FlaUI/FlaUI#364]
Hello,

Is there a way to Register to something in an AutomationElement, that then notifies me when the IsOffscreen Property changes?
I tried 
`element.RegisterPropertyChangedEvent(FlaUI.Core.Definitions.TreeScope.None, OnPropertyChanged, 
                                new PropertyId[] { new UIA3AutomationElementPropertyIds().IsOffscreen });`
but it did not work. Cannot find anything else that works. Any suggestions?

Thank you.

**Comment by Roemer** [comment]
That should be the correct way, but you might want to use `TreeScope.Element` and `automation.PropertyLibrary.Element.IsOffscreen` instead of a new `UIA3AutomationElementPropertyIds` object.

**Comment by lupusilviu** [comment]
Hello,

In the mean time, I tried this also:
` element.RegisterPropertyChangedEvent(FlaUI.Core.Definitions.TreeScope.Element,
                                OnNewPropChangedEvent, _automation.PropertyLibrary.Element.IsOffscreen);`

But to no success either.

**Comment by Roemer** [comment]
Did you check that it changes in FlaUInspect?

**Comment by Roemer** [comment]
And make sure that your automation element is not garbage collected as that clears the events I think.

**Comment by lupusilviu** [comment]
Should it be changing automatically? For me, FlaUInspect does not change even if I change the entire page. I have to retarget the Window to see changes.

In the same code, I am using with success 
` _window.RegisterStructureChangedEvent(FlaUI.Core.Definitions.TreeScope.Descendants, OnChangedChilren);`
And I have no proble with this. I will try to see if I can keep references of the objects. Maybe that is the problem.

**Comment by lupusilviu** [comment]
Seems it did not help either. This is the code portion:
`
....
private Dictionary<AutomationElement, PropertyChangedEventHandlerBase> _elements = new Dictionary<AutomationElement, PropertyChangedEventHandlerBase>();
....
if (element.IsOffscreen == true)
                        {
                            var eventGenerated = element.RegisterPropertyChangedEvent(FlaUI.Core.Definitions.TreeScope.Element,
                                OnNewPropChangedEvent, _automation.PropertyLibrary.Element.IsOffscreen);
                            _elements.Add(element, eventGenerated);
                        }`
I have a breakpoint there inside the IF, and I can confirm that it reaches it. So you say it should have worked.

**Comment by Roemer** [comment]
Strange, I just tried it with notepad and minimizing the window but it does not fire, although other properties like `BoundingRecangle` work flawlessly. This is probably because when an item is "offscreen", it maybe does not fire uia events. You might want to create a background task that checks for that property and some wait handlers. Also make sure that the "offscreen" really is that what you want as it is not set to false if an element is just outside of the windows bounds. Check with Inspect that offscreen really works or if you need something else (see for example #357).

**Comment by lupusilviu** [comment]
Hello,

Maybe it has to do with the fact that I am doing this on Chrome?
What I am trying to do, is update the search list of items automatically, when the Structure changes (which works), or when the scroll list moves the items into view or out of screen. The seconds part does not work. I am using UIA3, so I do not get any scroll element, just the buttons.
The buttons that are off screen have BoundingRectangle Emplty, and IsOffScreen=true. I tried attacking to both properties, but neither of thm worked. 

With FlaUInspector, I inspect a page, I see the same buttons with the same offscreen properties, and when I scroll, FlaUInspector does not change anything. I have to create a new instance to see any changes. But on the new instance, the buttons become IsOffScreen=false, and have a Bounding Rectangle.

**Comment by lupusilviu** [comment]
I discarded trying to use global events.
What I did is a Weapper over the AutomationElement, and on a thread, I check if any of the Properties I am interested in, change. If they change, I fire an event from there.
I will post the wrapper:

` 
class ClickableElementWrapper : IDisposable
    {
        #region Members
        private AutomationElement _element;
        #endregion Members

        #region Properties

        public System.Drawing.Rectangle ScreenArea { get; private set; }

        public Boolean IsOffScreen { get; private set; }

        #endregion Properties

        #region Constructor

        public ClickableElementWrapper(AutomationElement element)
        {
            _element = element;

            IsOffScreen = _element.FrameworkAutomationElement.IsOffscreen.ValueOrDefault;
            ScreenArea = _element.FrameworkAutomationElement.BoundingRectangle.ValueOrDefault;
        }

        #endregion Constructor

        #region IDisposable

        public void Dispose()
        {
            try
            {
                _element = null;
            }
            catch (Exception ex)
            {
            }
        }

        #endregion IDisposable

        #region Methods

        public bool HasChanges()
        {
            try
            {
                if (_element == null)
                    return false;

                var handledElement = _element.FrameworkAutomationElement;
                bool isOffScreenChanged = handledElement.IsOffscreen.ValueOrDefault != IsOffScreen;
                bool positionChanged =
                    ScreenArea.X != handledElement.BoundingRectangle.ValueOrDefault.X
                    || ScreenArea.Y != handledElement.BoundingRectangle.ValueOrDefault.Y;

                if (isOffScreenChanged == true || positionChanged == true)
                {
                    IsOffScreen = _element.FrameworkAutomationElement.IsOffscreen.ValueOrDefault;
                    ScreenArea = _element.FrameworkAutomationElement.BoundingRectangle.ValueOrDefault;
                    return true;
                }
            }
            catch { }

            return false;
        }
        #endregion Methods
    }
`
and this is the code that runs on the list of wrapper elements, that runs on a different thread:
`while (_token.IsCancellationRequested == false)
                {
                    Thread.Sleep(50);
                    bool anyChanges = false;

                    lock (_lockList)
                    {
                        foreach (ClickableElementWrapper item in _elements)
                        {
                            if (item.HasChanges() == true)
                                anyChanges = true;
                        }
                    }
                    if (anyChanges == true)
                        _onElementChangedCallback?.Invoke();
                }`
