### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by lupusilviu** [FlaUI/FlaUI#368]
Hello,

I am trying to improve the search performance of AutomationElements in an application.
At the moment, I found out that the standard methods are slower than a simple backtracking. But is there another way of improving the Search methods?

This method is faster than a .FindAllDescendants(docCondition). Any suggestions of doing a fast document Find?

```csharp
private void TryFindAllOfType(AutomationElement element, ControlType type, ref List<AutomationElement> result)
{
  try
  {
     foreach (AutomationElement item in element.FindAllChildren())
     {
       if (item.Properties.ControlType.ValueOrDefault == type)
        result.Add(item);
     else
       TryFindAllOfType(item, type, ref buttons);
     }
  }
 catch (Exception ex) {   }
}
```

**Comment by Rand-Random** [comment]
You aren’t respecting nesting of the same type, since you only call the recursion if the type doesn’t match.

Which I believe the method .FindAllDescendants(docCondition) isn’t doing, and also searches inside of controls of the given type.

**Comment by Roemer** [comment]
`FindAllDescendants` is almost always slower than any other slightly optimized search routine. The best would always be to get to your item by just using `FindFirstChild` with a specific condition on each level until you reach your desired item.
