### ISSUE TITLE
Property "Items" from menu not avaiable on notepad for example

### ISSUE THREAD

**Issue by jeangrahl** [FlaUI/FlaUI#369]
Menu options are not being available

![image](https://user-images.githubusercontent.com/13338336/92173602-6df7cd80-ee12-11ea-8cf9-4c99f10d7552.png)
![image](https://user-images.githubusercontent.com/13338336/92174071-8a940580-ee12-11ea-8696-b6ff61316e0a.png)

Example:
![image](https://user-images.githubusercontent.com/13338336/92175649-671d8a80-ee13-11ea-90e8-028b57e1bf95.png)
![image](https://user-images.githubusercontent.com/13338336/92175596-435a4480-ee13-11ea-921e-9888e81d940f.png)

Itens always null

**Comment by geovaneo** [comment]
Hi @jeangrahl , 
Notepad creates their sub-menus dinamically, so once you click on "Arquivo", it creates a new Menu directly under your Window(something similar to a floating menu). If you click on "Editar", it destroys whatever menu is loaded, and create a new one Named "Editar", also under the Window.
You cannot see it using FlaUI Inspect as it doesnt load new items dinamically. Try to "Log" all Children from Window object to check what I am talking about.

**Comment by Roemer** [comment]
@geovaneo Is right. You can also try this out with FlaUInspect and the Hover Mode. Then just go to your  submenu item and press ctrl and you will see the following:
![image](https://user-images.githubusercontent.com/393641/114088134-fe205880-98b4-11eb-9723-68e6c0a344ed.png)
