### ISSUE TITLE
when I do the mouse click action by FlaUI,It report "Could not send mouse input,ErrorCode:0"

### ISSUE THREAD

**Issue by fjwgrace** [FlaUI/FlaUI#371]
when I do the mouse click action by FlaUI,It report "Could not send mouse input,ErrorCode:0";I found the 360 Security Guard is Opened, When I Close 360, the error stop to report;

**Comment by Roemer** [comment]
I don't know  360 Security Guard but obviously it has detection for automatic mouse clicks / Win32 messages. Maybe you can just disable that one? Otherwise try to use other methods like `Invoke`.

**Comment by Roemer** [comment]
Closed due to no answer. Feel free to re-open if it is still an issue.
