### ISSUE TITLE
ffmpeg build is unavailable

### ISSUE THREAD

**Issue by Riabokrys** [FlaUI/FlaUI#372]
http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip resource is unavailable

**Code snippets**
var x = VideoRecorder.DownloadFFMpeg(_fileSystemPathCatalog.StagingRoot).Result;

Is there some other address that should be used instead?

**Comment by den-mentiei** [comment]
https://jeremylee.sh/bin.html
https://www.gyan.dev/ffmpeg/builds
?

**Comment by nogov** [comment]
https://github.com/FFmpeg/FFmpeg/releases

**Comment by nogov** [comment]
There is also an idea to replace ffmpeg with MediaProcessing to record test runs.

**Comment by Roemer** [comment]
The two official new channels are:
https://www.gyan.dev/ffmpeg/builds/
https://github.com/BtbN/FFmpeg-Builds/releases

I might think about creating a nuget package with ffmpeg binaries and just reference that one so it won't break in the future.

**Comment by Roemer** [comment]
Should be fixed in d5c9d9d0838c4fecf83dbd96502ede7e6045e7df

**Comment by snowmass** [comment]
Glad to see this fixed, thanks.  Will we see this in a NuGet release soon?
