### ISSUE TITLE
'Member not found. (0x80020003 (DISP_E_MEMBERNOTFOUND))'

### ISSUE THREAD

**Issue by prxy15** [FlaUI/FlaUI#376]
hi, im trying to perform an action on control.

```
var automation = new UIA3Automation();
var mainWindow = app.GetMainWindow(automation);
ConditionFactory cf = new ConditionFactory(new UIA3PropertyLibrary());

var elements =  mainWindow.FindAllDescendants(cf.ByName("Test Entry").And(cf.ByControlType(FlaUI.Core.Definitions.ControlType.Edit)));

 foreach ( var item in elements) {

                item.DrawHighlight();
                item.AsTextBox().Enter("Test text");
                
            }

```
`item.DrawHighlight();` works and make a red rectangle in control but  `item.AsTextBox().Enter("Test text");`  dispatch a excepction 
'Member not found. (0x80020003 (DISP_E_MEMBERNOTFOUND))'

any help will be appreciated

**Comment by prxy15** [comment]
I found a solution:

```
var elements =  mainWindow.FindFirstDescendant(cf.ByName("Test Entry").And(cf.ByControlType(FlaUI.Core.Definitions.ControlType.Edit)));

elements.DrawHighlight();
elements.DoubleClick();
Keyboard.Type("Test text");
```

work for me, thank you for this framework is awesome.

**Comment by Roemer** [comment]
You could also try `Focus()` on the element. Or set the value/text on the element instead of typing it which is more reliable if it is available.

**Comment by Roemer** [comment]
As you found a way to make it work, I will clsoe this issue. Thanks for the feedback.

**Comment by 1000374** [comment]
> I found a solution:
> 
> ```
> var elements =  mainWindow.FindFirstDescendant(cf.ByName("Test Entry").And(cf.ByControlType(FlaUI.Core.Definitions.ControlType.Edit)));
> 
> elements.DrawHighlight();
> elements.DoubleClick();
> Keyboard.Type("Test text");
> ```
> 
> work for me, thank you for this framework is awesome.
用Focus() 不能友好的区分元素，有概率会把所有字段发送到同一个元素上，移动坐标并双击的方式反而没问题，执行效率还能接收
