### ISSUE TITLE
Is FlaUI Supports Jenkins Integration

### ISSUE THREAD

**Issue by Vasanthi30** [FlaUI/FlaUI#387]
Hi Team,

The tests what we have written using falUI can be executed with jnekins pipeline? Can some one please explain how this can be done.

Thanks
Vasanthi

**Comment by Jazzman82** [comment]
Hi, 
we are using this in our automated tests in jenkins pipelines. So it is definitely possible :)
The biggest hurdle was to ensure that the framework has a desktop session (as mentioned also in the [wiki](https://github.com/FlaUI/FlaUI/wiki/FAQ#how-can-i-run-flaui-tests-on-a-build-serveragent))

We are using RealVNC for this: we have some VMs acting as Jenkins-Nodes which have the RealVNC-service installed and running and the pipeline then can start RealVNC-Viewer to open a client-session to localhost.

**Comment by dfev77** [comment]
@Vasanthi30 you are asking is the test you have written can be executed in jenkins, best would be to try it out, and if it is not working for some reasons also state the errors/behavior you encounter.

**Comment by Roemer** [comment]
Yes, FlaUI works perfectly from within Jenkins. If you have concrete questions on what you tried and what does not work, feel free to ask.
