### ISSUE TITLE
XPath expressions: Add support for more element properties to be addressed as attributes

### ISSUE THREAD

**Issue by nizwiz** [FlaUI/FlaUI#392]
**Describe the feature**
Currently, only 4 properties can be addressed as attributes in XPath expressions: AutomationId, Name, ClassName, HelpText. To make XPath expressions more useful when trying to automate applications that were not designed with automation in mind, it would be helpful to extend AutomationElementXPathNavigator to add support for other properties. Particularly useful examples would be **IsPassword**, **FullDescription**, **ItemType**, **AcceleratorKey**, **AccessKey**.
Maybe, using reflection or so, the code could even be adapted to automatically support all properties which can easily and canonically be converted to string.

I would be willing to contribute a pull request to add in support for more properties, but only in the same style as currently used in AutomationElementXPathNavigator  (I'm a C# layman and don't know anything about advanced techniques like reflection).

**Workarounds**
When trying to adress an element which can only be told apart from the rest by using properties other than the ControlType and the four supported XPath attributes, one needs to resort to using positions in the tree, like ".../Edit[4]"

**Comment by Roemer** [comment]
I added support for some more properties:
- IsPassword
- FullDescription
- ItemType
- AcceleratorKey
- AccessKey
- IsEnabled
- IsOffscreen
- ProcessId

I didn't found an easy way to add reflection there, so currently more properties need to be added manually.

**Comment by nizwiz** [comment]
Thanks a lot, much appreciated!
