### ISSUE TITLE
Is there any way to do image recognition with FlaUI?

### ISSUE THREAD

**Issue by sharpordie** [FlaUI/FlaUI#393]
I have to automate a QT application and it's mostly invisible from FlaUInspect. I wonder if it could be possible to do image recognition (identifying an area and clicking on it) with FlaUI?

**Comment by kungfux** [comment]
I would say FlaUI does not fit your needs. It has the capabilities to take screenshots and automate the mouse/keyboard but having no control positions makes it worthless. Moreover, FlaUI is not as cross-platform as QT, I guess.

**Comment by fredrikbondesson** [comment]
Perhaps better to use something like
http://sikulix.com/
which uses OpenCV as image recognition library

**Comment by Roemer** [comment]
FlaUI will probably support image assertions in the future (see the open PR). But that is only for comparing two images not for searching an image for something specific. You need to do that on your own with OpenCV or as mentioned already, use something that does that already.
Maybe check why your QT application does not support UIA? As far as I know, newer QT usually supports UIA fairly well.
