### ISSUE TITLE
Can't click button correctly, because the new window is showing gradually.

### ISSUE THREAD

**Issue by PhoenixLI812** [FlaUI/FlaUI#394]
**Hello,**
I'm testing a WPF project with FlaUI, and I know that "Retry" methods can wait for elements' presenting. However, I meet an amazing issue when i try to click a button in the new window which is showing gradually.
As the code below, after I click the "Load" button, there is a new "LoadWindow" showing gradually, and the second line will execute then and I get the new window. There is nothing abnormal till now. 
Nevertheless, when the third line execute, the mouse click in a wrong place, which is left the button and it make my test code doesn't work, as the picture shows below.

**CODE:**

      mainWindow.FindFirstDescendant(cf.ByName("Load")).AsButton().Click();
      var LoadWindow = Retry.WhileNull(() => mainWindow.FindFirstDescendant(cf.ByName("LoadWindow")).AsWindow(), TimeSpan.FromSeconds(60)).Result;
      LoadWindow.FindFirstDescendant(cf.ByName("Browse")).AsButton().Click();

**The LoadWindow:**
     ![image](https://user-images.githubusercontent.com/69836022/105684383-d9604a00-5f2f-11eb-987d-8e2ef8597463.png)

After thinking a lot, I guess maybe the computer click at the point showing below, but at this point the window is not present completely and the button is not avaliable either.
Of course adding thread.sleep before the third line does work, is there any solution here? 

**The computer click the browse button at the below point:**
![image](https://user-images.githubusercontent.com/69836022/105686031-bb93e480-5f31-11eb-8d79-91f2030a668e.png)

Expect for your replies, thanks very much!

**Comment by kungfux** [comment]
Does it mean if new window loads gradually that control's position change over time during loading? Just a guess, but will it help to use `Invoke()` instead of `Click()`?

**Comment by PhoenixLI812** [comment]
> Does it mean if new window loads gradually that control's position change over time during loading? Just a guess, but will it help to use `Invoke()` instead of `Click()`?

The Invoke() does really work, thank you kungfux O(∩_∩)O.
