### ISSUE TITLE
Besides automatically testing CSharp, you can also control C + + software, right?

### ISSUE THREAD

**Issue by bbhxwl** [FlaUI/FlaUI#396]
Besides automatically testing CSharp, you can also control C + + software, right?

When I click (), if the focus is not on the form, it seems that there will be an error.

I wonder if this thing can control the QQ of the computer and make a robot?

**Comment by kungfux** [comment]
Hi @bbhxwl.

> Besides automatically testing CSharp, you can also control C + + software, right

This automation library is not about C#, but about Windows UI automation. So, it does not really matter what language is used to build software. More important how it draws UI.

> When I click (), if the focus is not on the form, it seems that there will be an error.

It should not be so. I am able to click on inactive window control.

> I wonder if this thing can control the QQ of the computer and make a robot?

Not sure what does QQ stands for.

**Comment by Roemer** [comment]
You can automate everything that supports Windows UI Automation. Be it a C#, VB, Python, QT, C++ or whatever app. If you still have issues, please describe your problem in more details.
