### ISSUE TITLE
How to set name of pane in Flaui automation?

### ISSUE THREAD

**Issue by sercanmercan** [FlaUI/FlaUI#401]
There is a Pane type automation element that I can access, how can I set the name of Pane?

**Comment by dfev77** [comment]
Automation is used to access the UI elements and interact with them (click on buttons, read text, tick checkboxes). You do not set a control name from FlaUI/automation, you do is from the code of the application.

**Comment by Roemer** [comment]
As @dfev77 pointed out, this must be done by the application itself. In a WPF application for example, this is done with `AutomationProperties.AutomationId`.
