### ISSUE TITLE
Button click crashes application

### ISSUE THREAD

**Issue by tvinko** [FlaUI/FlaUI#404]
**Describe the bug**
Button click crashes application. Client application is running as Administrator.

**Code snippets**
Following code  throws exception **System.ArgumentNullException: 'Value cannot be null.Parameter name: element'**
`_window.FindAllDescendants(_conditionFactory.ByAutomationId("automationId"))[0].AsButton().Click();`

**Additional context**
Problematic function is:
```
public override bool TryGetClickablePoint(out Point point)
{
        // TryGetClickablePoint throws Value cannot be null.Parameter name: element'
	var success = NativeElement.TryGetClickablePoint(out System.Windows.Point outPoint);
	if (success)
	{
		point = new Point(outPoint.X.ToInt(), outPoint.Y.ToInt());
	}
	else
	{
		success = Properties.ClickablePoint.TryGetValue(out point);
	}
	return success;
}
```

However, if I patch code with following, it performs button click successfully:
```
public override bool TryGetClickablePoint(out Point point)
{
	point = new Point();
	bool success;
	try
	{
		success = NativeElement.TryGetClickablePoint(out System.Windows.Point outPoint);
		if (success)
		{
			point = new Point(outPoint.X.ToInt(), outPoint.Y.ToInt());
		}
	}
	catch (Exception ex)
	{
		success = Properties.ClickablePoint.TryGetValue(out point);
	}            
	return success;
}
```

**Comment by Roemer** [comment]
You're using UIA2 right? I cannot reproduce the issue you got. Which .NET version are you using? Can you provide a sample solution?
