### ISSUE TITLE
Populate Field in pane but off screen

### ISSUE THREAD

**Issue by RuBiiix** [FlaUI/FlaUI#405]
Hello, I am trying to populate values in a custom Windows application.

The window is set up so that all of the columns I need are held on the detailEditor window. 

However the actual GUI means that some of these columns are actually on a different tab which there seems to be no way to switch to this tab via code without actually clicking the tab - I cannot find a way to do this since the window could be anywhere on the user's screen.

I can populate any values on the first tab without issue but trying to populate on the second tab (While GUI still on the first tab) returns an error, I assume because the field can't be typed into.

var resonCdField = CrimsOrderEntryWindow.FindFirstDescendant(cf.ByAutomationId("detailEditor")).FindAllDescendants(cf.ByAutomationId("lueOReasonCd")); //Returns no targets
                    resonCdField.Where(x => x.ControlType.Equals(FlaUI.Core.Definitions.ControlType.Edit)).FirstOrDefault().AsTextBox().Enter(order.OrderReason);

![image](https://user-images.githubusercontent.com/79708088/109525921-eb428900-7aa9-11eb-9e6b-6c9c76ba43b5.png)

All of the fields in the below screenshot are held under the detailEditor window and there is only this one pane from FlaUInspect.

![image](https://user-images.githubusercontent.com/79708088/109526195-38265f80-7aaa-11eb-9e07-b4f67812239f.png)

Any help would be much appreciated.

Thanks

**Comment by Roemer** [comment]
Instead of `Enter` you could try the `ValuePattern` and set the value directly without keyboard. Alternatively, do you know on which tab which control is so you could click the appropriate tab?

**Comment by RuBiiix** [comment]
Hi Roemer 

Thanks for coming back on this. 

You're fix has worked and the field is now being populated.

//New code
CrimsOrderEntryWindow.FindFirstDescendant(cf.ByAutomationId("detailEditor")).FindAllDescendants(cf.ByAutomationId("lueOReasonCd")).Where(x => x.ControlType.Equals(FlaUI.Core.Definitions.ControlType.Edit)).FirstOrDefault().Patterns.Value.Pattern.SetValue(order.OrderReason);

Many thanks
