### ISSUE TITLE
Question: how to see when a text of Textblock is cutoff with FlaUI

### ISSUE THREAD

**Issue by kevinheyvaert** [FlaUI/FlaUI#412]
Is there a way how to see with FlaUI when a text in a textblock or other element is cutoff (not entirely visible)? I want to test localization of a WPF app (setting app to different language). I was checking online for UIAutomation information about it but I only see that your element needs the TextPattern and the TextPatternRange. 
https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/obtain-text-attributes-using-ui-automation 

But the textblock im using (I guess they are default one's, I only perform verification, not design the WPF app under test ), they don't have those patterns with the FlaUI Inspect tool. 

What are my options here? Do I create a new custom textblock with those patterns to retrieve the information? Or are there other options with FlaUI or other patterns that can be  used?

Is there someone is this community that can help with this? Or has experience with a situation like this?

Let me know.

Thanks for the answers.

**Comment by kevinheyvaert** [comment]
I just saw this teststack white issue of a couple of years ago:  https://github.com/TestStack/White/issues/519 . I see that @Roemer  closed thise one. Seems to be a hard issue to get it working with UIAutomation?

**Comment by Roemer** [comment]
I would say yes, creating an own Text control that either provides the TextAttributes or even your own AutomationProperty which exposes if the text is cutoff or not (which is set from your application).
