### ISSUE TITLE
implement rename folder

### ISSUE THREAD

**Issue by danipeer** [FlaUI/FlaUI#425]
Hi There,
is there any example how to implement a rename on a tree?
I mean, I have a tree with a dropmenu that has an option of "Rename"
when I click the "Rename" the item is ready for typing.
How do I implement the text change?

**Comment by DavidKarlas** [comment]
Try using:
Keyboard.Type("YourNewNameText");
Wait.UntilInputIsProcessed();
Keyboard.Type(VirtualKeyShort.RETURN);
