### ISSUE TITLE
Could not load the structure 'FlaUI.Core.WindowsAPI.INPUT' from assembly

### ISSUE THREAD

**Issue by ataliady** [FlaUI/FlaUI#427]
I'm writing a program for drag-dropping files across File Explorer.
When running the program in Visual Studio it works well.
After merging the assemblies into an executable (using ILMerge-GUI), when I run it I get the following error when reaching to mouse simulation: 

Could not load the structure 'FlaUI.Core.WindowsAPI.INPUT' from assembly 'FileExplorer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The structure is marked as eligible for type equivalence, but it has a method. 
  at FlaUI.Core.Input.Mouse.SendInput(Int32 x, Int32 y, UInt32 data, MouseEventFlags flags)
  at FlaUI.Core.Input.Mouse.Click(MouseButton mouseButton)
  at AppSimulations.cAppSimulations.SimulateFileOperation(String sourcePath, String destPath, String operation, String method)

*The merged dll's contain UA2, UA3, Core (version 3.2.0) and Interop.UIAutomationClient v10.0.19041

I Couldn't find any solution or any report of a similar issue.
What could possibly be the problem?

**Comment by Roemer** [comment]
Interesting error. Never seen that and when searching for it, you don't find much only one thread where it is questioned whether this is a bug in .NET/Windows. The only methods in `INPUT` are static helpers to create individual objects for mouse/keyboard. If you can try, you could refactor those methods out of this class and see if that works?
