### ISSUE TITLE
Failure in Button.Click is not detectable

### ISSUE THREAD

**Issue by ltjax** [FlaUI/FlaUI#437]
**Describe the bug**
Button.Click silently failed with `Could not send mouse input. ErrorCode: 5`. I would expect an exception or an error code, so we can detect the error and let our test fail.

**Code snippets**
```
var login = window.FindFirstDescendant(cf.ByAutomationId("LoginButton")).AsButton();
login.Click();
```

**Additional context**
We have a UI testing setup on our build agent. Normally, the tests ran as expected. But when one of us looked at the build agent using window's remote desktop connection, that engaged the lock screen (because it does that...), causing `Button.Click` to fail. Our tests still compeleted successfully because the error is only in the log and it took quite a while to detect this.

**Comment by Roemer** [comment]
Fixed with #460
