### ISSUE TITLE
Unable to select the nodes of a tree view

### ISSUE THREAD

**Issue by komyg** [FlaUI/FlaUI#443]
Hi,

I am trying to test an old Windows Forms application. The problem is that it has a tree control that doesn't show in the FlaUI inspector:

![image](https://user-images.githubusercontent.com/25157901/133247855-e0a4223b-6356-45de-8a17-cfdf2d8b2d71.png)

![image](https://user-images.githubusercontent.com/25157901/133247888-813144c9-91d1-41ce-ab7c-30a7f4886ecb.png)

As you can see the inspector only shows the pane containing the control and the scrollbar below.

I've also tried to select the tree items directly within the code:

```C#
var topLevelWindow = app.GetAllTopLevelWindows(automation);
var pane = topLevelWindow[0].FindFirstDescendant(cf => cf.ByAutomationId("1"));
var group = topLevelWindow[0].FindFirstDescendant(cf => cf.ByAutomationId("2"));
var children = group.FindAllChildren();
                
var tree = children[0].AsTree();
Console.WriteLine(tree.Items);
```

But the `tree.items` array is empty.

I've tried to make this work with both _UIA2_ and _UIA3_.

Is there another way to access this control?

**Comment by Roemer** [comment]
You could try with the treewalker. Do you see the controls in `inspect.exe` which uses the tree walker?

**Comment by komyg** [comment]
No. I've tried it, but got the same result/

**Comment by komyg** [comment]
Ok, thanks!
