### ISSUE TITLE
Working with DataItem to read contents

### ISSUE THREAD

**Issue by joebiker** [FlaUI/FlaUI#444]
I am using the following code to get an array of `DataItem`s (actually Automation Element[]):
```
  var rows = win.FindAllDescendants(_cf.ByControlType(
      FlaUI.Core.Definitions.ControlType.DataItem
  ));
```
However I am unable to read cells in my table.  WPF, UIA3

![image](https://user-images.githubusercontent.com/4908327/133829555-9d389015-5a22-42f0-a823-6529273c5176.png)

I reviewed https://github.com/FlaUI/FlaUI/issues/92 but was unable to assist me here.

Can you help?

**Comment by sharpordie** [comment]
The only way I found was to use OCR unfortunately. :(
