### ISSUE TITLE
WPF app launches Chrome, is there any way to use FlaUI to interact with Chrome?

### ISSUE THREAD

**Issue by lagetxa123** [FlaUI/FlaUI#447]
Hi,
I'm currently automating tests for a WPF application which at some stage it launches Chrome. I'm wondering if there's any way I can interact with the elements of Chrome using the same session.
I have tried to find Chrome elements using the frameworkId but I guess that I need to switch somehow from my app to the Chrome tab is being launched? Any suggestion?

Thanks in advance!

**Comment by artarik** [comment]
i use selenium for this

**Comment by Shrafe** [comment]
@lagetxa123 you should be able to attach to the Chrome process using FlaUI and interact with it. I would recommend using the powerful FlaUI Inspector tool; I used it to determine precisely which components to manipulate in various legacy programs for my use case.

**Comment by lagetxa123** [comment]
thanks for your suggestion :)! I will try it now and let you know!

**Comment by Roemer** [comment]
You can interact with chrome but a bit limited as chrome does not provide all UIA features. You can also enable more UIA features in chrome for example with the command line `--force-renderer-accessibility` in Chrome. See https://www.chromium.org/developers/design-documents/accessibility for details.

**Comment by lagetxa123** [comment]
I managed to interact with Chrome and all the web elements within the browser tab by navigating through the Desktop tree and focusing in the Chrome tab I was interested in. It works perfectly.
Thanks for your replies!

**Comment by Roemer** [comment]
Great so I'll close the issue then.
