### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'Interop.UIAutomationClient, Version=10.0.18362.0

### ISSUE THREAD

**Issue by AlMoCosta** [FlaUI/FlaUI#451]
Hello ! I am now trying to launch the simplest FlaUI project in Visual Studio Comm 2019 and get this message (below). The used .NET is 4.7.2. FlaUI installed via packages (see screenshot). Could you please suggest a solution for this problem? Thank you !

![image](https://user-images.githubusercontent.com/88190808/138682146-d02725e5-c5fc-4910-9b8f-ef383cd84266.png)

![image](https://user-images.githubusercontent.com/88190808/138682463-a6552627-58a0-498e-aaa6-380cc1873925.png)

![image](https://user-images.githubusercontent.com/88190808/138682334-81d43e84-2fad-4c44-918c-c7af6e263887.png)

![image](https://user-images.githubusercontent.com/88190808/138683122-0f0ab30f-ddfd-4a0d-86d8-48f9dfcfe7e2.png)

**Comment by Roemer** [comment]
Closing is at is solved.
