### ISSUE TITLE
Elements not being identified by Flaui while is shown in Inspect tool and the value property is incorrectly read.

### ISSUE THREAD

**Issue by Sandykrish02** [FlaUI/FlaUI#455]
Trying to automate a windows application with FlaUI and noticed some components are not recognized.
need to know if there are other ways to read the value from the element.
1.	Launch application immediately opens a window which has a Grid Pane.
2.	The opened window has an item to be selected from the grid (from the list of items) to proceed further.
3.	However UIA3 and UIA2 finds it difficult to get the element and its Value. (see below)
 
![image](https://user-images.githubusercontent.com/93434136/140612152-3b01a97b-16c5-469d-a1da-10bfc56217e5.png)

4.	In the above screenshot the Value is supposed to be “**Item to be selected from the list”** but instead it is [#30093].
       **Question:- How do i get the actual value from the application instead of the displayed [#30093] value?**
5.	While verifying in inspect.exe I noticed that the components are displayed but the same is not shown in FlauInspect.exe (screens below)
6.	SSC window has 7 subitems shown by Inspect while in Flauinspect.exe it shows only a button.
Inspect.exe
  
![image](https://user-images.githubusercontent.com/93434136/140612166-18bd06b5-8de2-4a42-a5df-50180a972e01.png)

Flauinspect.exe
 
![image](https://user-images.githubusercontent.com/93434136/140612169-5cf2b20f-a035-4d9b-bf98-3abe282a7a74.png)

**Comment by Sandykrish02** [comment]
@Roemer would you be able to help me here with the issue? is there a way to get the actual value of components not being read by flaui and which is displayed in Inspect.exe?

**Comment by firecrauter** [comment]
![image](https://user-images.githubusercontent.com/7044466/141302530-d14ac0af-564e-4037-bd6f-b5ce64af1ac3.png)

try .AsTextBox().Patterns.Value.PatternOrDefault?.Value.Value

**Comment by Sandykrish02** [comment]
@firecrauter thanks for your reply. Hope this works. let me check your solution and post a reply.

**Comment by Sandykrish02** [comment]
@firecrauter the solution works perfectly fine and gets the required value. Closing the issue as I got what i am looking for however elements are still missing in flauiinspect!
