### ISSUE TITLE
FlaUI fails to recognize the correct window when an application has a splash screen

### ISSUE THREAD

**Issue by gccops** [FlaUI/FlaUI#464]
Hello,

I am a new to FlaUI and still learning.

I am writing some codes to simulate the keyboard to input some characters to a Windows application (Not developed by .Net). When I start this Windows app, the splash screen comes up first and then the main screen is displayed in about 10-15 seconds.

The problem appears with the finding of UI elements. I use FlaUInspect.exe to find the elements’ automationID for the main window, but even the obvious elements can not be found (shows Object reference not set to an instance of an object).

I think that the splash screen was captured as the main window because I used the function FindAllDescendants to list all elements and can see the related stuff.

Do you know how to skip the splash screen?

It seems that the target application is hooked by FlaUI.Core.Application.Launch(), is there any way I can hook any sub window for my application dynamically at any time? 

Thanks.

**Comment by jolce95** [comment]
I have the probably same issue but with WPF application. So I can find the login screen and enter the user and password and log in to the application. Then I'm trying to find my open application screen. Could not find any item by name or class. And the application does not have any automationID after the login screen. For that, I'm using FlaUIinsept app. 
Also, I'm a beginner in FLAUI.

**Comment by osfresia** [comment]
Please provide screenshots of the app or the inspect.

**Comment by gccops** [comment]
The solution is to use FlaUI.Core.Application.Attach(processID) to skip splash screen and load the correct window form.
