### ISSUE TITLE
Is there any way to run UI automation scripts in Windows 10 new virtual desktop(not in active)

### ISSUE THREAD

**Issue by siddusri01** [FlaUI/FlaUI#472]
I coded a small script to press one, two, three buttons in calculator application, It is working fine in active desktop but if we shift to other  desktop. The script is getting failed. I knew UIAutomation's root node corresponds to the current active virtual desktop. but is there any way to fix the issue and make it work in non-interactive desktop

**Comment by Roemer** [comment]
No, many interactions rely on Mouse input and Keyboard events (which need the correct focus). So in most cases, running UI tests in an inactive Desktop won't work.
