### ISSUE TITLE
New FlaUI nuget release request

### ISSUE THREAD

**Issue by alex-ngan** [FlaUI/FlaUI#473]
Hi,

I do not know if this is the correct place to ask but, I wonder when there is a new release available? We would like to update our FlaUI nuget package to include the changes, where some methods in the FlaUITestBase are able to be overriden thanks to the changes made by johan-eriksson.

Thanks in advance!

Best regards,
Alex

**Comment by Roemer** [comment]
I finally released a new version and deprecated quite some stuff so it is easily possible to work and extend FlaUI with Visual Studio 2022.
