### ISSUE TITLE
Maximize and minimize window

### ISSUE THREAD

**Issue by LukeOwlclaw** [FlaUI/FlaUI#474]
**Describe the feature**
How to maximize, minimize, restore a `Window`?

**Workarounds**
I guess I could look for the maximize button. But there surely is a better way, is there?

**Comment by osfresia** [comment]
I think we still don't have the former .WindowsState.Maximize we had before but you can use the [Keyboard](https://github.com/FlaUI/FlaUI/wiki/Keyboard) instead of searching for the buttons.

**Comment by Roemer** [comment]
The `WindowPattern` has a method `SetWindowVisualState` you can use to set the desired states.

**Comment by SameerYoussef** [comment]
`window.Patterns.Window.Pattern.SetWindowVisualState(WindowVisualState.Maximized);`

🌮Kudos to you @Roemer for making my life better via your code!
