### ISSUE TITLE
Is it Possible to use UIA2Automation and UIA3Automation in 1 Project?

### ISSUE THREAD

**Issue by glennkimpo** [FlaUI/FlaUI#480]
Is it possible to automate UIA2 and UIA3 objects in 1 project?

We have an app that has a mixture of Win (e.g. combobox) and WPF (e.g. treeview) objects.
If I use UIA3Automation, the combobox encounters null reference error on .Select() method.
If I use UIA2Automation, the issue is resolved.

For the treeview, if I use UIA3Automation, the value of Name property is returned properly.
But if I use UIA2Automation, blank value is returned.

And what is weird is, I created 2 window object (1 UIA2 for combo box, 1 UIA3 for treeview), and on 1st pass, it works for the treeview, but once it executes the line of code for combo box, then if I set next statement back to the treeview code, it doesn't work anymore (returning blank for Name property).

            var winUIA3= AppHelperFlaUi.GetProcessWindowUIA3("AppInTest");
            var tvwObj = winUIA3.FindFirstDescendant(cf.ByAutomationId("treeView1")).AsTree();
            AppHelperFlaUi.SelectTreeViewItem(tvwObj , treePath);

            var winUIA2= AppHelperFlaUi.GetProcessWindow("AppInTest");
            var cboObj= winUIA2.FindFirstDescendant(cf.ByAutomationId("comboBox1")).AsComboBox();
            cboObj.Select(itemToSelect);

GetProcessWindow returns: targetWindow = appInTest.GetMainWindow(new UIA2Automation());

**Comment by Roemer** [comment]
It is a known issue that somehow and UIA framework is bound to a process. So you cannot use UIA2 and UIA3 in the same process, you need separate processes for each.
