### ISSUE TITLE
Can we run flaui automated test cases in parallel

### ISSUE THREAD

**Issue by bawarim** [FlaUI/FlaUI#492]
I have automated my tests using flaui. 
When I execute my test suite then it takes more than 10 hours to run. 
So is there any way that i can run my test in parallel? As we used to do in selenium grid.

**Comment by dfev77** [comment]
It all depends on your setup :smile: , but general OS and GUI interface behavior would not allow it (consider only window losing focus because another tests moves focus to another screen in order to run it's scenario).

Best you could do it to run them in separate jobs (for example using NUnit's test filter - at least 2 ways to do it or splitting the test library in multiple separate ones).
Sure you can also look to improve performance of the test (remove sleeps, optimize waits, etc.). I used at one point PostSharp to identify optimization candidates in our tests.

**Comment by bawarim** [comment]
Hi @dfev77 
I agree with your point, in running parallel test on same machine will create different problems. But I want to run my test in parallel on remote machines. So is there any way that we can execute from a single machine but my test will run on different remote machines? 
I have seen that we can achieve the parallel execution on remote machine using winappdriver + appium. 

But how can we perform the same using FLAUI?

**Comment by dfev77** [comment]
In the case of Appium you have a server and some clients (so multiple computers, and that is dictated by the purpose of Appium). Here you have just one which would run both the application under test and the test themselves.

FlaUI is not a test runner, just a lib to be used in tests to interact with the application.

Even when run on remote computer, the code actually still runs locally, the application is run "locally, on the remote computer" (unless I misunderstood your case).

So in the end to run in parallel on multiple machines you just have to start it on multiple machines, and that would be a topic related to the used tools (jenkins, bamboo, team fundation, etc.)

**Comment by SameerYoussef** [comment]
@Roemer I've been trying to run tests in parallel on a single Azure VM by starting a second user session through RDP then closing the window but leaving the session open - then using PsExec to launch the test for that second user. Sadly the tests still compete for mouse/keyboard/screen resources and fail. Do you simply run each test on its own VM?

**Comment by SameerYoussef** [comment]
Specifically I am getting the following exception when running two desktops on my VM:
```
System.ComponentModel.Win32Exception : Access is denied.

   at FlaUI.Core.Input.Keyboard.SendInput(UInt16 keyCode, Boolean isKeyDown, Boolean isScanCode, Boolean isExtended, Boolean isUnicode) in C:\x\FlaUI\src\FlaUI.Core\Input\Keyboard.cs:line 268
   at FlaUI.Core.Input.Keyboard.Type(Char character) in C:\x\FlaUI\src\FlaUI.Core\Input\Keyboard.cs:line 73
   at FlaUI.Core.Input.Keyboard.Type(String text) in C:\x\FlaUI\src\FlaUI.Core\Input\Keyboard.cs:line 22
   at FlaUI.Core.AutomationElements.TextBox.Enter(String value) in C:\x\FlaUI\src\FlaUI.Core\AutomationElements\TextBox.cs:line 90
   at FlaUI.Core.AutomationElements.TextBox.set_Text(String value) in C:\x\FlaUI\src\FlaUI.Core\AutomationElements\TextBox.cs:line 58
```
