### ISSUE TITLE
Couldn't run FLAUI tests on disconnected VM

### ISSUE THREAD

**Issue by bawarim** [FlaUI/FlaUI#494]
I am running my flaui test on a VM by taking RDP. 
But if I execute my tests and then close or disconnect the VM. Then my tests are getting failed. 

So is there any way that I can run my FLAUI tests on a VM in disconnected mode?

**Comment by Jteve-Sobs** [comment]
If you still want to use RDP:
Follow the steps [here](https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/keeping-computer-unlocked.html) in the section "Disconnect via a Batch File" and always disconnect using this batch file.

**Comment by kevinheyvaert** [comment]
When you close a Remote Desktop session on a remote computer, it locks out the computer, displaying the logon screen. In the locked mode, the user session on the computer does not have GUI, and any GUI tests on that computer will fail.

To avoid problems with GUI tests, use the [tscon](http://technet.microsoft.com/en-us/library/cc770988(v=ws.10).aspx) utility to disconnect from Remote Desktop. tscon returns the control to the original local session on the remote computer, bypassing the logon screen. All programs on the remote computer continue running normally, including GUI tests.

To disconnect from Remote Desktop, run the following command on the remote computer (in the Remote Desktop window) as an Administrator:

`%windir%\System32\tscon.exe RDP-Tcp#NNN /dest:console`
