### ISSUE TITLE
Optimization can be done on condition By.Name

### ISSUE THREAD

**Issue by Chevalier12** [FlaUI/FlaUI#501]
**Describe the bug**
var WinWindow = Desktop.FindAllDescendants(cf=> cf.ByName("Google")); takes 5 seconds more to find all descendants rather than var Windows = Desktop.FindAllChildren().Where(x=> x.Name.ToUpper().Contains("GOOGLE")); that will find it in less than a second.

**Code snippets**
            var automation = new UIA3Automation();
            var Desktop = automation.GetDesktop();
            Console.WriteLine(DateTime.Now); // 8/5/2022 11:56:19 AM
            var Windows = Desktop.FindAllChildren().Where(x=> x.Name.ToUpper().Contains("GOOGLE"));
            Console.WriteLine(DateTime.Now); // 8/5/2022 11:56:19 AM
            var WinWindow = Desktop.FindAllDescendants(cf=> cf.ByName("Google"));
            Console.WriteLine(DateTime.Now); // 8/5/2022 11:56:24 AM

As you can see, you can replicate the same behavior in LINQ much quicker than by using ByName.

**Comment by Roemer** [comment]
You cannot compare `FindAllChildren` with `FindAllDescendants`. Please use the same for both to compare.

**Comment by Chevalier12** [comment]
Even if I use Desktop.`FindFirstDescendant `or `FindFirstByXPath`, the runtime would still not compare with: Desktop.`FindAllChildren`().Where(x=> x.Name.ToUpper().Contains("GOOGLE"));.

Searching main windows on a desktop with `FindAllChildren `and a Linq command is the quickest you can go.

**Comment by Chevalier12** [comment]
> You cannot compare `FindAllChildren` with `FindAllDescendants`. Please use the same for both to compare.

How do you suppose I could use the same for both in this situation?

Desktop.FindAllChildren().Where(x=> x.Name.ToUpper().Contains("GOOGLE"));  **in this case, the condition would be the Linq command.**

Desktop.FindAllDescendants(cf=> cf.ByName("Google")); **and in this case the condition is the ConditionFactory.**

**Comment by Chevalier12** [comment]
From all of my preliminary tests I realized that XPath based searching is the quickest and the strongest, as you can see here:

```

            Console.WriteLine(DateTime.Now.ToString("HH:mm:ss:ffff")); //21:38:12:0539
            var var1 = automation.GetDesktop().FindAllByXPath("*[contains(@Name,'Google')]"); 
            Console.WriteLine(DateTime.Now.ToString("HH:mm:ss:ffff")); //21:38:12:6929
            var var2 = automation.GetDesktop().FindAllChildren().Where(x => x.Name.Contains("Google"));
            Console.WriteLine(DateTime.Now.ToString("HH:mm:ss:ffff")); //21:38:13:1948
```

Even XPath based searching puts to shame Linq based searching en-masse.

**Comment by Roemer** [comment]
> How do you suppose I could use the same for both in this situation?
> 
> Desktop.`FindAllChildren`().Where(x=> x.Name.ToUpper().Contains("GOOGLE")); **in this case, the condition would be the Linq command.**
> 
> Desktop.`FindAllDescendants`(cf=> cf.ByName("Google")); **and in this case the condition is the ConditionFactory.**

The first one gets all children of the desktop (which are probably around 20) and searches all of them that match the name.
The second one searches ALL descendants, which are thousands if not 100'000s and is therefore of course much much slower.
