### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Chevalier12** [FlaUI/FlaUI#502]
When attempting to find all descendants of an AutomationElement and then filtering it via Linq, this error occurs as you can see in the below picture.

I'm testing this on Google Chrome, selecting the first google chrome window and then searching for the Address bar.

![image](https://user-images.githubusercontent.com/49100023/183745296-e9601f79-8c01-4007-b08a-5156d33bc58e.png)
![image](https://user-images.githubusercontent.com/49100023/183745557-49cf69dc-7ff9-43c2-9f50-128004291a60.png)

**Comment by pm90pl** [comment]
```x.Name?.StartsWith("Address")??false```
But what is more important - the way you're trying to achieve the goal is insufficient. Please, construct a proper locator instead of iterating through ALL app descendants. There is a lot of inter-process communication that kills your application.

**Comment by Roemer** [comment]
As said above, this is a pretty bad approach to find items. If you know the name, use the `ConditionFactory` to search for items with the specific name instead of searching all descendants and filter with linq.
