### ISSUE TITLE
FLAUI for Linux.

### ISSUE THREAD

**Issue by vlaterz** [FlaUI/FlaUI#512]
Hello, i used FlaUI to get application window element tree on Windows OS. But now i need to write the same thing for Linux. Is there any analogs for doing that? I use .NET (C#).

**Comment by pm90pl** [comment]
FlaUI is based on UIAutomation mechanism - which is an internal Windows implementation. So FlaUI cannot work on Linux.

**Comment by vlaterz** [comment]
> FlaUI is based on UIAutomation mechanism - which is an internal Windows implementation. So FlaUI cannot work on Linux.

Yes, I know, but may be someone knows about something like FLAUI, but for linux?

**Comment by pm90pl** [comment]
I don't want to be rude, but it's not a question related to FlaUI bugs/suggestions and should be asked on StackOverflow for instance.

**Comment by vlaterz** [comment]
I already did this =)
Ok, thanks for your answers

**Comment by igorrecioh** [comment]
@vlaterz I have just found this for Linux: https://github.com/ldtp/ldtp2

Quite old and does not seem to be maintained....

Hope it helps

**Comment by Roemer** [comment]
As already written, FlaUI is based on Microsoft UIA, so it does not work on Linux.
