### ISSUE TITLE
Macos support?

### ISSUE THREAD

**Issue by agonzalezm** [FlaUI/FlaUI#518]
Does Flaui works for NET 6 on Macos?

We are using this code to get the url of the active browser and need to do the same in macos, is it possible to run on macos or any alternative to do the same in mac?

 if (process.ToLower() == "chrome.exe")
                {
                    isBrowser = true;
                    var window = _UIA.FromHandle(handle);

                    var editControl = window.FindAllDescendants(cf => cf.ByControlType(FlaUI.Core.Definitions.ControlType.Edit));
                    if (editControl != null)
                    {
                        var first = editControl.LastOrDefault();
                        if (first != null)
                        {
                            browserURL = clearUrl(first.AsTextBox().Text);
                            return;
                        }
                    }
                }

**Comment by Roemer** [comment]
No, FlaUI is based on Microsoft UI Automation Framework which is only on Windows, so it is not possible to use it on MacOS.
