### ISSUE TITLE
DrawHighlight method not working

### ISSUE THREAD

**Issue by KillerKaninchen1284** [FlaUI/FlaUI#520]
**Describe the bug**
In my programm I want to loop over each element in a window and show a highlight. But it wont recognize "DrawHighlight"

**Code snippets**
int processId = 17828;
            var app = FlaUI.Core.Application.Attach(processId);
            var automation = new UIA3Automation();
            var mainwindow = app.GetMainWindow(automation, TimeSpan.MinValue);
            /////////////////////////////

            ConditionFactory cf = new ConditionFactory(new UIA2PropertyLibrary());
            var Elements = mainwindow.FindAllDescendants(cf.ByControlType(ControlType.Button));
            Console.WriteLine("ho");
            var i = 0;
            foreach (var child in Elements)
            {
                i++;
                if (child.ControlType == FlaUI.Core.Definitions.ControlType.Button)
                    Console.WriteLine(child); Console.WriteLine("HI");
                child.DrawHighlight(false, 1000));

**Additional context**
Thats the errror(in German)
ü
Fehler	CS1061	"AutomationElement[]" enthält keine Definition für "DrawHighlight", und es konnte keine zugängliche DrawHighlight-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "AutomationElement[]" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
(in English)

Error CS1061 "AutomationElement[]" does not contain a definition for "DrawHighlight" and no accessible DrawHighlight extension method could be found that accepts a first argument of type "AutomationElement[]" (possibly a using directive or assembly reference is missing).

**Comment by Roemer** [comment]
`DrawHighlight` is an extension method, so you need to add the using for `FlaUI.Core.AutomationElements` (which your IDE should already propose to you).
