### ISSUE TITLE
i want to click or invoke a win32 dialog messagebox button, but it can' work and show exception .

### ISSUE THREAD

**Issue by Lanceliyp** [FlaUI/FlaUI#524]
**Describe the bug**
exception as :
Managed debugging assistants "NonComVisibleBaseClass" : "performed QueryInterface call, request to provide COM visible managed class" Ms. Internal. AutomationProxies. WindowsButton "class interface. However, due to the class from the COM visible class "Ms. Internal. AutomationProxies. ProxyHwnd" derived, QueryInterface call will fail. The goal is to avoid base classes that are not visible to COM being subject to COM version rules."
**Code snippets**
```csharp
UIA3Automation uIA3 = new UIA3Automation();
var desk = uIA3.GetDesktop();
var main = desk.FindFirstChild(cf => cf.ByClassName("#32770"));

if (main != null && main.Name.Contains("AMD Cleanup"))
{
    var button1 = main.FindFirstDescendant(cf => cf.ByControlType(FlaUI.Core.Definitions.ControlType.Button).And(cf.ByAutomationId("7")))?.AsButton();

    if (button1 != null)
    {
        Console.WriteLine(button1.Name);
    }

    button1.Click();
    //    button1?.Invoke();
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/74600392/199639157-cd8d8c13-ecfc-4c68-a328-2ed72d398d32.png)

**Additional context**

**Comment by Roemer** [comment]
Where exactly does the error happen? Did you try run the code elevated (as admin)?

**Comment by Lanceliyp** [comment]
Hi @Roemer ，Thanks for your responding,  I have solved it by running it through the administrator.
