### ISSUE TITLE
Labview exe Automation

### ISSUE THREAD

**Issue by csierer** [FlaUI/FlaUI#541]
**Describe the bug**
I was given an application written in Labview. I tried running the UIA2 and UIA3 and the only things that can be found are the title bar. all the buttons and objects actually in the application can't be found. I tried FLAUI Inspect and the same thing, it found the title bar but nothing else in UIA3 interop and UIA2 managed.

what can i do to automate this application

**Code snippets**
Show code snippets of the part that did not work.

**Screenshots**
Add screenshots of FlaUInspect/Inspect to show your controls with issues.

**Additional context**
![Untitled](https://user-images.githubusercontent.com/81707546/207991645-181c1d0e-5731-4523-b949-32f1308723c0.png)

**Comment by Roemer** [comment]
If the application does not provide any accessibility information, there's not much you can do. The only thing you could do is using the mouse or keyboard to automate it as good as possible.
