### ISSUE TITLE
Test failing when upgrading app from .NET4.6.2 to .NET4.8

### ISSUE THREAD

**Issue by igorrecioh** [FlaUI/FlaUI#569]
**Describe the bug**
My app was using .NET4.6.2 and all test were passing fine. However, I have recently updated to .NET4.8 and some of them have started to fail. The issue can be seen when interacting with ComboBox elements.

**Code snippets**
Before, with .NET4.6.2 I was able to select ComboBox items with this:
```csharp
_partWindow.FindFirstByXPath("MY XPATH").AsComboBox().Items[0].Select();
```
After, with .NET4.8, I cannot use the previous way and I need to do this:
```csharp
_Window.FindFirstByXPath("MY XPATH").Click();
_Window.FindFirstByXPath("MY COMBO ITEM").Click();
```

**Screenshots**
N/A

**Additional context**
In some other cases, I had to change XPaths, and even concatenate the search like this:

```csharp
// .NET4.6.2
_Window.FindFirstByXPath("FullXpath").AsTextBox().Enter(diameter);

// .NET4.8
_Window.FindFirstByXPath("//Window[@Name='Blah']/Window[@Name='Blah']").FindFirstByXPath("Blah").FindFirstByXPath("//Pane").FindFirstByXPath("//Edit")).AsTextBox().Enter("2");
```

Why is this happening? Can we do something on our side to avoid this?

Thanks a lot

**Comment by Roemer** [comment]
Unfortunately, Microsoft does not treat UI-Automation very well. Changes are almost always undocumented. There are also a lot of inconsistencies between WinForms, WPF, Universal-Apps and between all .NET versions. Considering .NET 4.8 is the final classic version, you should not run into similar issues again until you switch to a much more recent one.
