### ISSUE TITLE
When Flaui will support .net core 8.0

### ISSUE THREAD

**Issue by WangZhuoyuan0226** [FlaUI/FlaUI#611]
Hi team, I wander when Flaui will support .net core 8.0, or is the latest Falui 4.0.0 already works well in .net core 8.0? Since I need to upgrade my c# project from 6.0 to 8.0. 
Waiting for your reply.
Thanks!

**Comment by fundthmcalculus** [comment]
I've used it with `.net8.0-windows` without issue.

**Comment by LevYas** [comment]
I updated to .net 8 without any issues too

**Comment by Roemer** [comment]
Even thou it already works with 8.0, I now finally added the build target for 8.0. A release is coming very soon.
