### ISSUE TITLE
 FindFirstDescendant error

### ISSUE THREAD

**Issue by weifan999** [FlaUI/FlaUI#625]
When the form has not yet appeared, when the FindFirstDescendant statement is executed, null is not returned. Instead, the code seems to terminate execution and no error is prompted. It just cannot continue to run. How to solve this problem?

`automation.GetDesktop().FindFirstDescendant(x => x.ByAutomationId("DeluxeLoginFormNewChild")`

**Comment by weifan999** [comment]
My other computer can return null, so that I can decide to continue waiting, but this laptop is also a win10 system. I don't know why this is happening. Does it have anything to do with my computer?

**Comment by PeterHevesi** [comment]
don't use automation.GetDesktop().FindFirstDescendant() because it searches all elements in all opened apps, which might take extremely long... Rather use automation.GetDesktop().FindFirstChild() instead

**Comment by Roemer** [comment]
@PeterHevesi is right. This method potentially searches thru a lot of controls and maybe in the end results in a COM timeout on your laptop. Maybe because it is slower or because it has more programs running that are searched. Limit your search to an application or other filters to prevent this.

**Comment by pferreirafabricio** [comment]
> don't use automation.GetDesktop().FindFirstDescendant() because it searches all elements in all opened apps, which might take extremely long... Rather use automation.GetDesktop().FindFirstChild() instead

Thank you! That worked.
