### ISSUE TITLE
Inquiry About Maintenance and Potential Collaboration

### ISSUE THREAD

**Issue by jose-artur** [FlaUI/FlaUI#663]
@Roemer 
### Discussed in https://github.com/FlaUI/FlaUI/discussions/661

<div type='discussions-op-text'>

<sup>Originally posted by **jose-artur** November 28, 2024</sup>
Hello @Roemer ,
 My team and I are exploring automation tools, and we are particularly interested in using FlaUI for our project.

We  wanted to inquire about its current maintenance status. Additionally, we also want to understand if there are opportunities for collaboration.

Would it be possible to arrange a conversation with you to discuss this further? Our team is also open to contributing to the project, potentially as maintainers.
Looking forward to your response!</div>

**Comment by Roemer** [comment]
I just answered in the discussion. Somehow I don't get mail notifications for them. I'll close the issue here so we can stick to the discussion in https://github.com/FlaUI/FlaUI/discussions/661
